package com.eResorts;


	import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;

	import com.itextpdf.text.Document;

	import com.itextpdf.text.Element;

	import com.itextpdf.text.Phrase;

	import com.itextpdf.text.pdf.ColumnText;

	import com.itextpdf.text.pdf.PdfAction;

	import com.itextpdf.text.pdf.PdfContentByte;

	import com.itextpdf.text.pdf.PdfPTable;

	import com.itextpdf.text.pdf.PdfPageEventHelper;

import com.itextpdf.text.pdf.PdfWriter;

	public class HeaderAndFooter extends PdfPageEventHelper {

	protected Phrase header;

	protected PdfPTable footer;

	private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
			Font.NORMAL, BaseColor.BLACK);

	public HeaderAndFooter() {
		

	header = new Phrase("**** Header ****");
/*
	footer = new PdfPTable(1);

	footer.setTotalWidth(150);

	footer.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);

	footer.addCell(new Phrase(new Chunk(

	"**** Footer summary Report generated by JavaGenious****")

	.setAction(new PdfAction(PdfAction.FIRSTPAGE))));
*/
	} 

	public void onEndPage(PdfWriter writer, Document document) {

	PdfContentByte cb = writer.getDirectContent();

	ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT, new Phrase(String.format("%d", writer.getPageNumber()),

	redFont), (document

	.right() - document.left())

	/ 2 + document.leftMargin(), document.bottom() - 10, 0);

	

	}

	}

