/*
SQLyog Community v9.02 
MySQL - 5.5.12 : Database - fms
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`fms` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `fms`;

/*Table structure for table `accommodation` */

DROP TABLE IF EXISTS `accommodation`;

CREATE TABLE `accommodation` (
  `LocationID` varchar(100) NOT NULL,
  `LocationName` varchar(200) DEFAULT NULL,
  `LocationImage` varchar(200) DEFAULT NULL,
  `LocationDesc` tinytext,
  PRIMARY KEY (`LocationID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `accommodation` */

insert  into `accommodation`(`LocationID`,`LocationName`,`LocationImage`,`LocationDesc`) values ('L001','Goa','Goa1.jpg','Our resort is 5km from beach\r\n\n'),('L002','Coorg','Coorg.jpg','Our resort is 5Km from this location'),('L003','Manali','Manali.jpg','Our resort is 15kms from this location'),('L004','Kodaikanal','Kodaikanal.jpg','Our resort is 10kms from this location'),('L005','Munnar','Munnar.jpg','Our resort is 15kms from this location');

/*Table structure for table `account` */

DROP TABLE IF EXISTS `account`;

CREATE TABLE `account` (
  `account_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `account_name` varchar(64) DEFAULT NULL,
  `account_lob` bigint(20) DEFAULT NULL,
  `account_client` varchar(64) DEFAULT NULL,
  `account_location` bigint(20) DEFAULT NULL,
  `account_head` varchar(20) DEFAULT NULL,
  `account_desc` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  KEY `FK_account_lob` (`account_lob`),
  KEY `FK_account_location` (`account_location`),
  CONSTRAINT `FK_account_location` FOREIGN KEY (`account_location`) REFERENCES `location` (`location_id`),
  CONSTRAINT `FK_account_lob` FOREIGN KEY (`account_lob`) REFERENCES `lob` (`lob_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Data for the table `account` */

insert  into `account`(`account_id`,`account_name`,`account_lob`,`account_client`,`account_location`,`account_head`,`account_desc`) values (1,'TRISEPT',1,'abc coRP',1,'1','sadsad'),(2,'BLUESTAR',1,'blueSTAR',1,'1','dfsdffsfs'),(3,'TRISEPT',1,'trisept',1,'WSDSDQQ','CSADCDCSC'),(4,'TRISEPT',1,'TRISEPT',1,'DILIP','xcdsdcsd'),(5,'TRISEPT',2,'TRISEPT',2,'DILIP','zx ccdsscsc');

/*Table structure for table `bookingsinfo` */

DROP TABLE IF EXISTS `bookingsinfo`;

CREATE TABLE `bookingsinfo` (
  `BookingID` varchar(100) NOT NULL,
  `ResortID` varchar(100) DEFAULT NULL,
  `RoomID` varchar(100) DEFAULT NULL,
  `LocationName` varchar(100) DEFAULT NULL,
  `UserID` varchar(100) DEFAULT NULL,
  `MemberType` varchar(100) DEFAULT NULL,
  `RoomCharges` float DEFAULT NULL,
  `From` date DEFAULT NULL,
  `To` date DEFAULT NULL,
  `BookingStatus` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`BookingID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `bookingsinfo` */

insert  into `bookingsinfo`(`BookingID`,`ResortID`,`RoomID`,`LocationName`,`UserID`,`MemberType`,`RoomCharges`,`From`,`To`,`BookingStatus`) values ('B01','R001','R0011','Goa','kalyan','Platinum',375,'2008-02-26','2008-02-29','CheckedOut'),('B02','R002','R0024','Coorg','kalyan','Platinum',375,'2008-02-22','2008-02-25','CheckedOut'),('B03','R001','R0011','Goa','kalyan','Platinum',375,'2008-02-01','2008-02-06','CheckedOut'),('B04','R001','R0011','Goa','Subhas','Gold',400,'2008-02-22','2008-02-22','CheckedOut');

/*Table structure for table `city` */

DROP TABLE IF EXISTS `city`;

CREATE TABLE `city` (
  `city_info` text,
  `city_code` varchar(5) DEFAULT NULL,
  `city_name` varchar(64) DEFAULT NULL,
  `city_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `country_id` bigint(20) NOT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `city_image` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`city_id`),
  KEY `fk_city_country1` (`country_id`),
  KEY `city_name` (`city_name`),
  KEY `city_code` (`city_code`),
  CONSTRAINT `fk_city_country1` FOREIGN KEY (`country_id`) REFERENCES `country` (`country_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1356 DEFAULT CHARSET=utf8;

/*Data for the table `city` */

insert  into `city`(`city_info`,`city_code`,`city_name`,`city_id`,`country_id`,`latitude`,`longitude`,`city_image`) values ('Varanaci','VAR','Varanasi',1,1,NULL,NULL,NULL),(NULL,'TIA','Tirana',2,13,NULL,NULL,NULL),(NULL,'AUH','Abu Dhabi ',3,14,NULL,NULL,NULL),(NULL,'DXB','Dubai',4,14,NULL,NULL,NULL),(NULL,'SSH','Sharjah',5,14,NULL,NULL,NULL),(NULL,'BUE','Buenos Aires',6,15,NULL,NULL,NULL),(NULL,'YRV','Yerevan',7,16,NULL,NULL,NULL),(NULL,'AIA','Antigua ',8,17,NULL,NULL,NULL),('jxjzxznxznxznx',NULL,'Graz',9,18,NULL,NULL,NULL),(NULL,'INN','Innsbruck',10,18,NULL,NULL,NULL),(NULL,'KAP','Kaprun',11,18,NULL,NULL,NULL),(NULL,'KIT','Kitzbuehel',12,18,NULL,NULL,NULL),(NULL,'KLA','Klagenfurt',13,18,NULL,NULL,NULL),(NULL,'LNZ','Linz',14,18,NULL,NULL,NULL),(NULL,'POE','Poertschach am Woerthersee',15,18,NULL,NULL,NULL),(NULL,'SEE','Seefeld',16,18,NULL,NULL,NULL),(NULL,'SPL','St. Polten',17,18,NULL,NULL,NULL),(NULL,'SVT','St. Veit',18,18,NULL,NULL,NULL),(NULL,'SZG','Salzburg',19,18,NULL,NULL,NULL),(NULL,'VCH','Villach',20,18,NULL,NULL,NULL),(NULL,'VIE','Vienna',21,18,NULL,NULL,NULL),(NULL,'ZAS','Zell-am-See',22,18,NULL,NULL,NULL),(NULL,'ADE','Adelaide',23,19,NULL,NULL,NULL),(NULL,'AIB','Airlie Beach',24,19,NULL,NULL,NULL),(NULL,'ALS','Alice Springs',25,19,NULL,NULL,NULL),(NULL,'BSB','Brisbane',26,19,NULL,NULL,NULL),(NULL,'CAA','Canberra',27,19,NULL,NULL,NULL),(NULL,'CRN','Cairns',28,19,NULL,NULL,NULL),(NULL,'DAW','Darwin',29,19,NULL,NULL,NULL),(NULL,'FIA','Fraser Island',30,19,NULL,NULL,NULL),(NULL,'GCS','Gold Coast',31,19,NULL,NULL,NULL),(NULL,'HUV','Hunter Valley',32,19,NULL,NULL,NULL),(NULL,'MEL','Melbourne',33,19,NULL,NULL,NULL),(NULL,'MRW','Margaret River Wine Region',34,19,NULL,NULL,NULL),(NULL,'PAM','Palm Cove',35,19,NULL,NULL,NULL),(NULL,'PEH','Perth',36,19,NULL,NULL,NULL),(NULL,'PTI','Port Douglas',37,19,NULL,NULL,NULL),(NULL,'SHN','Sunshine Coast',38,19,NULL,NULL,NULL),(NULL,'SYD','Sydney',39,19,NULL,NULL,NULL),(NULL,'TAS','Tasmania',40,19,NULL,NULL,NULL),(NULL,'TWV','Townsville',41,19,NULL,NULL,NULL),(NULL,'BAK','Baku',42,20,NULL,NULL,NULL),(NULL,'ANT','Antwerp',43,21,NULL,NULL,NULL),(NULL,'BRG','Brugge',44,21,NULL,NULL,NULL),(NULL,'BRU','Brussels',45,21,NULL,NULL,NULL),(NULL,'CRL','Charleroi',46,21,NULL,NULL,NULL),(NULL,'GEK','Genk',47,21,NULL,NULL,NULL),(NULL,'GNT','Ghent',48,21,NULL,NULL,NULL),(NULL,'LEU','Leuven',49,21,NULL,NULL,NULL),(NULL,'LIE','Liege',50,21,NULL,NULL,NULL),(NULL,'MEC','Mechelen',51,21,NULL,NULL,NULL),(NULL,'NAM','Namur',52,21,NULL,NULL,NULL),(NULL,'OST','Ostend',53,21,NULL,NULL,NULL),(NULL,'WVE','Wavre',54,21,NULL,NULL,NULL),(NULL,'MNM','Manama',55,22,NULL,NULL,NULL),(NULL,'NAS','Nassau',56,23,NULL,NULL,NULL),(NULL,'PID','Paradise Island ',57,23,NULL,NULL,NULL),(NULL,'MSQ','Minsk',58,24,NULL,NULL,NULL),(NULL,'SVJ','Sarajevo',59,25,NULL,NULL,NULL),(NULL,'BME','Belem',60,26,NULL,NULL,NULL),(NULL,'BSX','Brasilia',61,26,NULL,NULL,NULL),(NULL,'CWB','Curitiba',62,26,NULL,NULL,NULL),(NULL,'FDI','Foz do Iguacu',63,26,NULL,NULL,NULL),(NULL,'FTZ','Fortaleza',64,26,NULL,NULL,NULL),(NULL,'NAT','Natal',65,26,NULL,NULL,NULL),(NULL,'PDF','Praia do Forte',66,26,NULL,NULL,NULL),(NULL,'RAR','Angra dos Reis',67,26,NULL,NULL,NULL),(NULL,'RIO','Rio de Janeiro',68,26,NULL,NULL,NULL),(NULL,'SAO','Sao Paulo',69,26,NULL,NULL,NULL),(NULL,'SSA','Salvador',70,26,NULL,NULL,NULL),(NULL,'BBB','Barbados',71,27,NULL,NULL,NULL),(NULL,'BGX','Burgas & South Black Sea Coast',72,28,NULL,NULL,NULL),(NULL,'BVE','Borovets',73,28,NULL,NULL,NULL),(NULL,'SOF','Sofia',74,28,NULL,NULL,NULL),(NULL,'VNA','Varna',75,28,NULL,NULL,NULL),(NULL,'MOX','Montreal',76,29,NULL,NULL,NULL),(NULL,'MTB','Mont Tremblant',77,29,NULL,NULL,NULL),(NULL,'QBC','Quebec City',78,29,NULL,NULL,NULL),(NULL,'TRT','Toronto',79,29,NULL,NULL,NULL),(NULL,'VCR','Vancouver',80,29,NULL,NULL,NULL),(NULL,'YOW','Ottawa',81,29,NULL,NULL,NULL),(NULL,'YYC','Calgary',82,29,NULL,NULL,NULL),(NULL,'HGZ','Hangzhou',83,30,NULL,NULL,NULL),(NULL,'NGB','Ningbo',84,30,NULL,NULL,NULL),(NULL,'PEK','Beijing',85,30,NULL,NULL,NULL),(NULL,'SHG','Shanghai',86,30,NULL,NULL,NULL),(NULL,'SYA','Sanya',87,30,NULL,NULL,NULL),(NULL,'SZH','Suzhou',88,30,NULL,NULL,NULL),(NULL,'TSN','Tianjin',89,30,NULL,NULL,NULL),('gfgjghjhk','XIY','Xian',90,30,NULL,NULL,NULL),(NULL,'DUV','Dubrovnik',91,31,NULL,NULL,NULL),(NULL,'IOB','Island of Brac',92,31,NULL,NULL,NULL),(NULL,'OPA','Opatija',93,31,NULL,NULL,NULL),(NULL,'SPI','Split',94,31,NULL,NULL,NULL),(NULL,'TCR','Trogir',95,31,NULL,NULL,NULL),(NULL,'ZAG','Zagreb',96,31,NULL,NULL,NULL),(NULL,'VRD','Varadero',97,32,NULL,NULL,NULL),(NULL,'CUR','Curacao',98,33,NULL,NULL,NULL),(NULL,'AYI','Ayia Napa',99,34,NULL,NULL,NULL),(NULL,'LAR','Larnaca',100,34,NULL,NULL,NULL),(NULL,'LSS','Limassol',101,34,NULL,NULL,NULL),(NULL,'NCS','Nicosia',102,34,NULL,NULL,NULL),(NULL,'PAP','Paphos',103,34,NULL,NULL,NULL),(NULL,'PRS','Protaras',104,34,NULL,NULL,NULL),(NULL,'BNO','Brno',105,35,NULL,NULL,NULL),(NULL,'CES','Cesky Krumlov',106,35,NULL,NULL,NULL),(NULL,'KAV','Karlovy Vary',107,35,NULL,NULL,NULL),(NULL,'MLZ','Marianske Lazne',108,35,NULL,NULL,NULL),(NULL,'OLM','Olomouc',109,35,NULL,NULL,NULL),(NULL,'OVT','Ostrava',110,35,NULL,NULL,NULL),(NULL,'PIL','Pilsen',111,35,NULL,NULL,NULL),(NULL,'PRG','Prague',112,35,NULL,NULL,NULL),(NULL,'AAL','Aalborg',113,36,NULL,NULL,NULL),(NULL,'AAR','Aarhus',114,36,NULL,NULL,NULL),(NULL,'CPH','Copenhagen',115,36,NULL,NULL,NULL),(NULL,'HSN','Horsens',116,36,NULL,NULL,NULL),(NULL,'KLD','Kolding',117,36,NULL,NULL,NULL),(NULL,'ODE','Odense',118,36,NULL,NULL,NULL),(NULL,'VEJ','Vejle',119,36,NULL,NULL,NULL),(NULL,'AEX','Alexandria',120,37,NULL,NULL,NULL),(NULL,'ASW','Aswan',121,37,NULL,NULL,NULL),(NULL,'CAI','Cairo',122,37,NULL,NULL,NULL),(NULL,'HRH','Hurghada',123,37,NULL,NULL,NULL),(NULL,'LXR','Luxor',124,37,NULL,NULL,NULL),(NULL,'SSE','Sharm El Sheikh',125,37,NULL,NULL,NULL),(NULL,'TBF','Taba',126,37,NULL,NULL,NULL),(NULL,'TLN','Tallinn',127,38,NULL,NULL,NULL),(NULL,'ESP','Espoo',128,39,NULL,NULL,NULL),(NULL,'FOS','Forssa',129,39,NULL,NULL,NULL),(NULL,'HAE','Hameenlinna',130,39,NULL,NULL,NULL),(NULL,'HEL','Helsinki',131,39,NULL,NULL,NULL),(NULL,'HYV','Hyvinkaa',132,39,NULL,NULL,NULL),(NULL,'IIS','Iisalmi',133,39,NULL,NULL,NULL),(NULL,'IKA','Ikaalinen',134,39,NULL,NULL,NULL),(NULL,'IMA','Imatra',135,39,NULL,NULL,NULL),(NULL,'JOS','Joensuu',136,39,NULL,NULL,NULL),(NULL,'JYV','Jyvaskyla',137,39,NULL,NULL,NULL),(NULL,'KAJ','Kajaani',138,39,NULL,NULL,NULL),(NULL,'KEM','Kemi',139,39,NULL,NULL,NULL),(NULL,'KOI','Koli',140,39,NULL,NULL,NULL),(NULL,'KOK','Kokkola',141,39,NULL,NULL,NULL),(NULL,'KOT','Kotka',142,39,NULL,NULL,NULL),(NULL,'KOU','Kouvola',143,39,NULL,NULL,NULL),(NULL,'KUO','Kuopio',144,39,NULL,NULL,NULL),(NULL,'KUU','Kuusamo',145,39,NULL,NULL,NULL),(NULL,'LAH','Lahti',146,39,NULL,NULL,NULL),(NULL,'LAP','Lappeenranta',147,39,NULL,NULL,NULL),(NULL,'MKL','Mikkeli',148,39,NULL,NULL,NULL),(NULL,'NOK','Nokia',149,39,NULL,NULL,NULL),(NULL,'OUL','Oulu',150,39,NULL,NULL,NULL),(NULL,'POF','Pori',151,39,NULL,NULL,NULL),(NULL,'RMA','Rauma',152,39,NULL,NULL,NULL),(NULL,'ROI','Rovaniemi',153,39,NULL,NULL,NULL),(NULL,'SAF','Salo',154,39,NULL,NULL,NULL),(NULL,'SJK','Seinajoki',155,39,NULL,NULL,NULL),(NULL,'SOK','Sodankyla',156,39,NULL,NULL,NULL),(NULL,'TAH','Tahkovuori',157,39,NULL,NULL,NULL),(NULL,'TMP','Tampere',158,39,NULL,NULL,NULL),(NULL,'TUK','Turku',159,39,NULL,NULL,NULL),(NULL,'VAS','Vaasa',160,39,NULL,NULL,NULL),(NULL,'AEP','Aix en Provence',161,4,NULL,NULL,NULL),(NULL,'AJC','Ajaccio',162,4,NULL,NULL,NULL),(NULL,'AMB','Amboise',163,4,NULL,NULL,NULL),(NULL,'AMI','Amiens',164,4,NULL,NULL,NULL),(NULL,'ANB','Antibes',165,4,NULL,NULL,NULL),(NULL,'ANC','Annecy',166,4,NULL,NULL,NULL),(NULL,'ANG','Angers',167,4,NULL,NULL,NULL),(NULL,'ANN','Annemasse',168,4,NULL,NULL,NULL),(NULL,'ARL','Arles',169,4,NULL,NULL,NULL),(NULL,'AVI','Avignon',170,4,NULL,NULL,NULL),(NULL,'AXB','Aix-les-Bains',171,4,NULL,NULL,NULL),(NULL,'BAY','Bayeux',172,4,NULL,NULL,NULL),(NULL,'BBS','Brides-les-Bains',173,4,NULL,NULL,NULL),(NULL,'BDX','Bordeaux',174,4,NULL,NULL,NULL),(NULL,'BIA','Biarritz',175,4,NULL,NULL,NULL),(NULL,'BLI','Blois',176,4,NULL,NULL,NULL),(NULL,'BRX','Briancon',177,4,NULL,NULL,NULL),(NULL,'BTI','Bastia',178,4,NULL,NULL,NULL),(NULL,'BTS','Brest',179,4,NULL,NULL,NULL),(NULL,'BYN','Bayonne',180,4,NULL,NULL,NULL),(NULL,'CAE','Caen',181,4,NULL,NULL,NULL),(NULL,'CHA','Chartres',182,4,NULL,NULL,NULL),(NULL,'CHT','Chantilly',183,4,NULL,NULL,NULL),(NULL,'CHX','Chamonix',184,4,NULL,NULL,NULL),(NULL,'CHY','Chambery',185,4,NULL,NULL,NULL),(NULL,'CLR','Clermont-Ferrand',186,4,NULL,NULL,NULL),(NULL,'CLS','Calais',187,4,NULL,NULL,NULL),(NULL,'CLV','Calvi',188,4,NULL,NULL,NULL),(NULL,'CMR','Colmar',189,4,NULL,NULL,NULL),(NULL,'CNN','Cannes',190,4,NULL,NULL,NULL),(NULL,'CRC','Carcassonne',191,4,NULL,NULL,NULL),(NULL,'DEA','Deauville',192,4,NULL,NULL,NULL),(NULL,'DIJ','Dijon',193,4,NULL,NULL,NULL),(NULL,'DLB','Divonne-les-Bains',194,4,NULL,NULL,NULL),(NULL,'DND','Dinard',195,4,NULL,NULL,NULL),(NULL,'EVI','Evian-les-Bains',196,4,NULL,NULL,NULL),(NULL,'EZE','Eze',197,4,NULL,NULL,NULL),(NULL,'FJU','Frejus',198,4,NULL,NULL,NULL),(NULL,'FVO','Ferney-Voltaire',199,4,NULL,NULL,NULL),(NULL,'GRN','Grenoble',200,4,NULL,NULL,NULL),(NULL,'HON','Honfleur',201,4,NULL,NULL,NULL),(NULL,'ILA','Isola 2000',202,4,NULL,NULL,NULL),(NULL,'LBA','La Baule ',203,4,NULL,NULL,NULL),(NULL,'LEH','Le Havre',204,4,NULL,NULL,NULL),(NULL,'LIL','Lille',205,4,NULL,NULL,NULL),(NULL,'LOU','Lourdes',206,4,NULL,NULL,NULL),(NULL,'LRO','La Rochelle',207,4,NULL,NULL,NULL),(NULL,'LRT','Lorient',208,4,NULL,NULL,NULL),(NULL,'LYO','Lyon',209,4,NULL,NULL,NULL),(NULL,'MEG','Megeve',210,4,NULL,NULL,NULL),(NULL,'MEN','Menton',211,4,NULL,NULL,NULL),(NULL,'MET','Metz',212,4,NULL,NULL,NULL),(NULL,'MMS','Mont St Michel',213,4,NULL,NULL,NULL),(NULL,'MON','Montpellier',214,4,NULL,NULL,NULL),(NULL,'MRS','Marseille',215,4,NULL,NULL,NULL),(NULL,'MUL','Mulhouse',216,4,NULL,NULL,NULL),(NULL,'NAN','Nancy',217,4,NULL,NULL,NULL),(NULL,'NCE','Nice',218,4,NULL,NULL,NULL),(NULL,'NIM','Nimes',219,4,NULL,NULL,NULL),(NULL,'NNT','Nantes',220,4,NULL,NULL,NULL),(NULL,'ORL','Orleans',221,4,NULL,NULL,NULL),(NULL,'PAR','Paris',222,4,NULL,NULL,NULL),(NULL,'POI','Poitiers',223,4,NULL,NULL,NULL),(NULL,'QUI','Quimper',224,4,NULL,NULL,NULL),(NULL,'REI','Reims',225,4,NULL,NULL,NULL),(NULL,'REN','Rennes',226,4,NULL,NULL,NULL),(NULL,'ROV','Rouen',227,4,NULL,NULL,NULL),(NULL,'SAM','Saint-Malo',228,4,NULL,NULL,NULL),(NULL,'SBG','Strasbourg',229,4,NULL,NULL,NULL),(NULL,'SIO','Saint-Emilion',230,4,NULL,NULL,NULL),(NULL,'SJC','Saint-Jean-Cap-Ferrat',231,4,NULL,NULL,NULL),(NULL,'SMR','Saumur',232,4,NULL,NULL,NULL),(NULL,'SNA','Saint-Nazaire',233,4,NULL,NULL,NULL),(NULL,'SPA','Sophia Antipolis',234,4,NULL,NULL,NULL),(NULL,'STZ','Saint-Tropez',235,4,NULL,NULL,NULL),(NULL,'TON','Toulon',236,4,NULL,NULL,NULL),(NULL,'TOU','Toulouse',237,4,NULL,NULL,NULL),(NULL,'TRS','Tours',238,4,NULL,NULL,NULL),(NULL,'VNS','Vannes',239,4,NULL,NULL,NULL),(NULL,'TBI','Tbilisi',240,41,NULL,NULL,NULL),(NULL,'AAC','Aachen',241,42,NULL,NULL,NULL),(NULL,'AUG','Augsburg',242,42,NULL,NULL,NULL),(NULL,'BBA','Baden-Baden',243,42,NULL,NULL,NULL),(NULL,'BCG','Berchtesgaden',244,42,NULL,NULL,NULL),(NULL,'BER','Berlin',245,42,NULL,NULL,NULL),(NULL,'BHG','Braunschweig',246,42,NULL,NULL,NULL),(NULL,'BON','Bonn',247,42,NULL,NULL,NULL),(NULL,'BRE','Bremen',248,42,NULL,NULL,NULL),(NULL,'BRH','Bad Reichenhall',249,42,NULL,NULL,NULL),(NULL,'CGN','Cologne',250,42,NULL,NULL,NULL),(NULL,'DRE','Dresden',251,42,NULL,NULL,NULL),(NULL,'DTW','Dortmund',252,42,NULL,NULL,NULL),(NULL,'DUS','Dusseldorf',253,42,NULL,NULL,NULL),(NULL,'ERF','Erfurt',254,42,NULL,NULL,NULL),(NULL,'ESS','Essen',255,42,NULL,NULL,NULL),(NULL,'FDT','Freudenstadt',256,42,NULL,NULL,NULL),(NULL,'FRA','Frankfurt',257,42,NULL,NULL,NULL),(NULL,'FRE','Freiburg',258,42,NULL,NULL,NULL),(NULL,'FRI','Friedrichshafen',259,42,NULL,NULL,NULL),(NULL,'FUS','Fuessen',260,42,NULL,NULL,NULL),(NULL,'GRE','Gera',261,42,NULL,NULL,NULL),(NULL,'HAM','Hamburg',262,42,NULL,NULL,NULL),(NULL,'HAN','Hannover',263,42,NULL,NULL,NULL),(NULL,'HEI','Heidelberg',264,42,NULL,NULL,NULL),(NULL,'HPE','Halle',265,42,NULL,NULL,NULL),(NULL,'KIE','Kiel',266,42,NULL,NULL,NULL),(NULL,'KRS','Karlsruhe',267,42,NULL,NULL,NULL),(NULL,'LDU','Lindau (Lake Constance)',268,42,NULL,NULL,NULL),(NULL,'LEV','Leverkusen',269,42,NULL,NULL,NULL),(NULL,'LPZ','Leipzig',270,42,NULL,NULL,NULL),(NULL,'LUE','Luebeck',271,42,NULL,NULL,NULL),(NULL,'MAB','Magdeburg',272,42,NULL,NULL,NULL),(NULL,'MCH','Monchengladbach',273,42,NULL,NULL,NULL),(NULL,'MNH','Mannheim',274,42,NULL,NULL,NULL),(NULL,'MNZ','Mainz',275,42,NULL,NULL,NULL),(NULL,'MUC','Munich',276,42,NULL,NULL,NULL),(NULL,'MUN','Muenster',277,42,NULL,NULL,NULL),(NULL,'NUE','Nuremberg',278,42,NULL,NULL,NULL),(NULL,'OBS','Oberhausen',279,42,NULL,NULL,NULL),(NULL,'PAS','Passau',280,42,NULL,NULL,NULL),(NULL,'RKO','Rostock',281,42,NULL,NULL,NULL),(NULL,'ROT','Rothenburg ob der Tauber',282,42,NULL,NULL,NULL),(NULL,'SCH','Schwerin',283,42,NULL,NULL,NULL),(NULL,'STT','Stuttgart',284,42,NULL,NULL,NULL),(NULL,'TRI','Trier',285,42,NULL,NULL,NULL),(NULL,'WEI','Weimar',286,42,NULL,NULL,NULL),(NULL,'WFE','Wolfsburg',287,42,NULL,NULL,NULL),(NULL,'WIE','Wiesbaden',288,42,NULL,NULL,NULL),(NULL,'WRZ','Wuerzburg',289,42,NULL,NULL,NULL),(NULL,'ZWM','Wismar',290,42,NULL,NULL,NULL),(NULL,'GIB','Gibraltar',291,43,NULL,NULL,NULL),(NULL,'GNA','Grenada',292,44,NULL,NULL,NULL),(NULL,'ATH','Athens',293,45,NULL,NULL,NULL),(NULL,'AXD','Alexandroupolis',294,45,NULL,NULL,NULL),(NULL,'CIO','Chios',295,45,NULL,NULL,NULL),(NULL,'CNT','Corinthos',296,45,NULL,NULL,NULL),(NULL,'CRF','Corfu',297,45,NULL,NULL,NULL),(NULL,'CRT','Crete',298,45,NULL,NULL,NULL),(NULL,'HKD','Halkidiki',299,45,NULL,NULL,NULL),(NULL,'JSS','Spetses',300,45,NULL,NULL,NULL),(NULL,'KLX','Kalamata',301,45,NULL,NULL,NULL),(NULL,'KSG','Kos',302,45,NULL,NULL,NULL),(NULL,'LNS','Lemnos',303,45,NULL,NULL,NULL),(NULL,'LRA','Larissa',304,45,NULL,NULL,NULL),(NULL,'MYK','Mykonos',305,45,NULL,NULL,NULL),(NULL,'NAX','Naxos',306,45,NULL,NULL,NULL),(NULL,'OIS','Ios',307,45,NULL,NULL,NULL),(NULL,'PAG','Paros',308,45,NULL,NULL,NULL),(NULL,'PLS','Pylos',309,45,NULL,NULL,NULL),(NULL,'RHO','Rhodes',310,45,NULL,NULL,NULL),(NULL,'SKA','Skiathos',311,45,NULL,NULL,NULL),(NULL,'SKG','Thessaloniki',312,45,NULL,NULL,NULL),(NULL,'SMI','Samos',313,45,NULL,NULL,NULL),(NULL,'SNI','Santorini',314,45,NULL,NULL,NULL),(NULL,'THS','Thassos',315,45,NULL,NULL,NULL),(NULL,'VSL','Volos',316,45,NULL,NULL,NULL),(NULL,'HKG','Hong Kong',317,46,NULL,NULL,NULL),(NULL,'BUD','Budapest',318,47,NULL,NULL,NULL),(NULL,'GYO','Gyor',319,47,NULL,NULL,NULL),(NULL,'LAB','Lake Balaton',320,47,NULL,NULL,NULL),(NULL,'AKU','Akureyri',321,48,NULL,NULL,NULL),(NULL,'BOE','Borgarnes',322,48,NULL,NULL,NULL),(NULL,'EGI','Egilsstadir',323,48,NULL,NULL,NULL),(NULL,'FLU','Fludir',324,48,NULL,NULL,NULL),(NULL,'HVA','Hvalfjordur',325,48,NULL,NULL,NULL),(NULL,'KEF','Keflavik',326,48,NULL,NULL,NULL),(NULL,'KRK','Kirkjubaejarkaustur',327,48,NULL,NULL,NULL),(NULL,'MYV','Myvatn',328,48,NULL,NULL,NULL),(NULL,'REY','Reykjavik',329,48,NULL,NULL,NULL),(NULL,'SLS','Selfoss',330,48,NULL,NULL,NULL),(NULL,'BXL','Bali',331,49,NULL,NULL,NULL),(NULL,'LOP','Lombok',332,49,NULL,NULL,NULL),(NULL,'HYD','Hyderabad',333,1,NULL,NULL,NULL),('Ahmedabad city description',NULL,'Ahmedabad',334,1,32,65,NULL),(NULL,'BLR','Bangalore',335,1,NULL,NULL,NULL),('Mumbai',NULL,'Mumbai',336,1,NULL,NULL,NULL),(NULL,'CCU','Kolkata',337,1,NULL,NULL,NULL),('Chennai',NULL,'Chennai',338,1,NULL,NULL,NULL),(NULL,'DEL','New Delhi',339,1,NULL,NULL,NULL),('IS India\'s smallest state by area and the fourth smallest by population. Located in West India in the region known as the Konkan, it is bounded by the state of Maharashtra to the north, and by Karnataka to the east and south, while the Arabian ','GOA','Goa',340,1,NULL,NULL,NULL),(NULL,'HYB','Hyderabad',341,1,NULL,NULL,NULL),(NULL,'JAI','Jaipur',342,1,NULL,NULL,NULL),(NULL,'NGP','Nagpur',343,1,NULL,NULL,NULL),(NULL,'PUN','Pune',344,1,NULL,NULL,NULL),(NULL,'SHI','Shimla',345,1,NULL,NULL,NULL),(NULL,'ATE','Athlone',346,51,NULL,NULL,NULL),(NULL,'CCV','Co. Cavan',347,51,NULL,NULL,NULL),(NULL,'COL','Co. Leitrim',348,51,NULL,NULL,NULL),(NULL,'COM','Co. Mayo',349,51,NULL,NULL,NULL),(NULL,'COR','Cork',350,51,NULL,NULL,NULL),(NULL,'COW','Co. Wexford',351,51,NULL,NULL,NULL),(NULL,'CUF','Co. Offaly',352,51,NULL,NULL,NULL),(NULL,'DOG','Co. Donegal',353,51,NULL,NULL,NULL),(NULL,'DUB','Dublin',354,51,NULL,NULL,NULL),(NULL,'GAL','Galway',355,51,NULL,NULL,NULL),(NULL,'KEE','Kenmare',356,51,NULL,NULL,NULL),(NULL,'KIL','Killarney',357,51,NULL,NULL,NULL),(NULL,'LIM','Limerick',358,51,NULL,NULL,NULL),(NULL,'RSC','Co. Roscommon',359,51,NULL,NULL,NULL),(NULL,'SLG','Sligo',360,51,NULL,NULL,NULL),(NULL,'TRL','Tralee',361,51,NULL,NULL,NULL),(NULL,'WAT','Waterford',362,51,NULL,NULL,NULL),(NULL,'DED','Dead Sea',363,52,NULL,NULL,NULL),(NULL,'EIL','Eilat',364,52,NULL,NULL,NULL),('Holy City of CHristrian Community','JRS','Jerusalem',365,52,190,80,NULL),(NULL,'TIB','Tiberias',366,52,NULL,NULL,NULL),(NULL,'TLV','Tel Aviv',367,52,NULL,NULL,NULL),(NULL,'ABO','Alberobello',368,53,NULL,NULL,NULL),(NULL,'AGG','Agrigento',369,53,NULL,NULL,NULL),(NULL,'ALH','Sardinia- Alghero',370,53,NULL,NULL,NULL),(NULL,'AMA','Amalfi - Ravello',371,53,NULL,NULL,NULL),(NULL,'ANA','Ancona',372,53,NULL,NULL,NULL),(NULL,'ASS','Assisi',373,53,NULL,NULL,NULL),(NULL,'AZZ','Arezzo',374,53,NULL,NULL,NULL),(NULL,'BAI','Bari',375,53,NULL,NULL,NULL),(NULL,'BCA','Brescia',376,53,NULL,NULL,NULL),(NULL,'BEG','Bergamo',377,53,NULL,NULL,NULL),(NULL,'BLQ','Bologna',378,53,NULL,NULL,NULL),(NULL,'BOZ','Bolzano',379,53,NULL,NULL,NULL),(NULL,'BRP','Brindisi',380,53,NULL,NULL,NULL),(NULL,'CBX','Calabria',381,53,NULL,NULL,NULL),(NULL,'CGI','Sardinia- Cagliari',382,53,NULL,NULL,NULL),(NULL,'CMO','Lake Como',383,53,NULL,NULL,NULL),(NULL,'CPR','Capri Island',384,53,NULL,NULL,NULL),(NULL,'CQT','Cinque Terre',385,53,NULL,NULL,NULL),(NULL,'CSA','Caserta',386,53,NULL,NULL,NULL),(NULL,'CSD','Sardinia- Costa Smeralda',387,53,NULL,NULL,NULL),(NULL,'CTN','Catania',388,53,NULL,NULL,NULL),(NULL,'FIU','Fiuggi',389,53,NULL,NULL,NULL),(NULL,'FLI','Forli',390,53,NULL,NULL,NULL),(NULL,'FLR','Florence',391,53,NULL,NULL,NULL),(NULL,'FOD','Ischia Island',392,53,NULL,NULL,NULL),(NULL,'FOM','Forte dei Marmi',393,53,NULL,NULL,NULL),(NULL,'GAS','Sardinia- Gulf of Asinara',394,53,NULL,NULL,NULL),(NULL,'GEN','Genoa',395,53,NULL,NULL,NULL),(NULL,'GSS','Grosseto',396,53,NULL,NULL,NULL),(NULL,'GUB','Gubbio',397,53,NULL,NULL,NULL),(NULL,'HCE','Chieti',398,53,NULL,NULL,NULL),(NULL,'ISD','Elba Island',399,53,NULL,NULL,NULL),(NULL,'LAK','Lake Garda',400,53,NULL,NULL,NULL),(NULL,'LCC','Lucca',401,53,NULL,NULL,NULL),(NULL,'LCE','Lecce',402,53,NULL,NULL,NULL),(NULL,'LKM','Lake Maggiore',403,53,NULL,NULL,NULL),(NULL,'MES','Messina',404,53,NULL,NULL,NULL),(NULL,'MIL','Milan',405,53,NULL,NULL,NULL),(NULL,'MOD','Modena',406,53,NULL,NULL,NULL),(NULL,'MTI','Montecatini Terme',407,53,NULL,NULL,NULL),(NULL,'MTV','Mantova',408,53,NULL,NULL,NULL),(NULL,'NAP','Naples & Pompei',409,53,NULL,NULL,NULL),(NULL,'OLB','Sardinia- Olbia',410,53,NULL,NULL,NULL),(NULL,'ORI','Sardinia- Oristano',411,53,NULL,NULL,NULL),(NULL,'ORV','Orvieto',412,53,NULL,NULL,NULL),(NULL,'OTR','Otranto',413,53,NULL,NULL,NULL),(NULL,'PAD','Padua',414,53,NULL,NULL,NULL),(NULL,'PEA','Pesaro',415,53,NULL,NULL,NULL),(NULL,'PLM','Palermo',416,53,NULL,NULL,NULL),(NULL,'PMA','Parma',417,53,NULL,NULL,NULL),(NULL,'POS','Positano',418,53,NULL,NULL,NULL),(NULL,'PSA','Pisa',419,53,NULL,NULL,NULL),(NULL,'PTF','Portofino & Rapallo',420,53,NULL,NULL,NULL),(NULL,'PTO','Prato',421,53,NULL,NULL,NULL),(NULL,'PUG','Perugia',422,53,NULL,NULL,NULL),(NULL,'RAV','Ravenna',423,53,NULL,NULL,NULL),(NULL,'RCN','Riccione',424,53,NULL,NULL,NULL),(NULL,'RGG','Reggio Emilia',425,53,NULL,NULL,NULL),(NULL,'RIM','Rimini',426,53,NULL,NULL,NULL),(NULL,'ROM','Rome',427,53,NULL,NULL,NULL),(NULL,'SAE','Salerno - Cilento',428,53,NULL,NULL,NULL),(NULL,'SAV','Savona',429,53,NULL,NULL,NULL),(NULL,'SEA','Sardinia- Santa Teresa Gallura',430,53,NULL,NULL,NULL),(NULL,'SER','Sanremo',431,53,NULL,NULL,NULL),(NULL,'SIE','Siena',432,53,NULL,NULL,NULL),(NULL,'SIR','Syracuse',433,53,NULL,NULL,NULL),(NULL,'SNX','Sardinia- Nuoro',434,53,NULL,NULL,NULL),(NULL,'SOR','Sorrento',435,53,NULL,NULL,NULL),(NULL,'SSP','Sardinia- San Pietro Island',436,53,NULL,NULL,NULL),(NULL,'TAO','Taormina',437,53,NULL,NULL,NULL),(NULL,'TRE','Trento',438,53,NULL,NULL,NULL),(NULL,'TRP','Trapani',439,53,NULL,NULL,NULL),(NULL,'TRV','Treviso',440,53,NULL,NULL,NULL),(NULL,'TST','Trieste',441,53,NULL,NULL,NULL),(NULL,'TUR','Turin',442,53,NULL,NULL,NULL),(NULL,'ULY','Ulysses Riviera',443,53,NULL,NULL,NULL),(NULL,'URB','Urbino',444,53,NULL,NULL,NULL),(NULL,'VAG','Viareggio',445,53,NULL,NULL,NULL),(NULL,'VCE','Venice',446,53,NULL,NULL,NULL),(NULL,'VER','Verona',447,53,NULL,NULL,NULL),(NULL,'VIN','Vicenza',448,53,NULL,NULL,NULL),(NULL,'FMT','Falmouth',449,54,NULL,NULL,NULL),(NULL,'MBJ','Montego Bay',450,54,NULL,NULL,NULL),(NULL,'NEG','Negril',451,54,NULL,NULL,NULL),(NULL,'OCJ','Ocho Rios ',452,54,NULL,NULL,NULL),(NULL,'RNW','Runaway Bay',453,54,NULL,NULL,NULL),(NULL,'AMM','Amman',454,55,NULL,NULL,NULL),(NULL,'AQJ','Aqaba',455,55,NULL,NULL,NULL),(NULL,'PTA','Petra',457,55,NULL,NULL,NULL),(NULL,'FUK','Fukuoka',458,9,NULL,NULL,NULL),(NULL,'NAG','Nagoya',459,9,NULL,NULL,NULL),(NULL,'NRT','Narita',460,9,NULL,NULL,NULL),(NULL,'OKA','Okinawa',461,9,NULL,NULL,NULL),(NULL,'OSA','Osaka',462,9,NULL,NULL,NULL),(NULL,'SPK','Sapporo',463,9,NULL,NULL,NULL),(NULL,'TOK','Tokyo',464,9,NULL,NULL,NULL),(NULL,'UKY','Kyoto',465,9,NULL,NULL,NULL),(NULL,'ATS','Astana',466,57,NULL,NULL,NULL),(NULL,'PNH','Phnom Penh',467,58,NULL,NULL,NULL),(NULL,'REP','Siem Reap',468,58,NULL,NULL,NULL),(NULL,'SUL','Seoul',469,59,NULL,NULL,NULL),(NULL,'LPJ','Liepaja',470,60,NULL,NULL,NULL),(NULL,'RIG','Riga',471,60,NULL,NULL,NULL),(NULL,'BEY','Beirut',472,61,NULL,NULL,NULL),(NULL,'SLC','St Lucia',473,62,NULL,NULL,NULL),(NULL,'DRK','Druskininkai',474,63,NULL,NULL,NULL),(NULL,'KNS','Kaunas',475,63,NULL,NULL,NULL),(NULL,'KPD','Klaipeda',476,63,NULL,NULL,NULL),(NULL,'MJP','Marijampole',477,63,NULL,NULL,NULL),(NULL,'VLS','Vilnius',478,63,NULL,NULL,NULL),(NULL,'LUX','Luxembourg',479,64,NULL,NULL,NULL),(NULL,'MCU','Macau',480,65,NULL,NULL,NULL),(NULL,'AGA','Agadir',481,66,NULL,NULL,NULL),(NULL,'CAS','Casablanca',482,66,NULL,NULL,NULL),(NULL,'ESU','Essaouira',483,66,NULL,NULL,NULL),(NULL,'MKH','Marrakech',484,66,NULL,NULL,NULL),(NULL,'RBA','Rabat',485,66,NULL,NULL,NULL),(NULL,'CNU','Cancun',486,68,NULL,NULL,NULL),(NULL,'GDL','Guadalajara',487,68,NULL,NULL,NULL),(NULL,'LCS','Los Cabos',488,68,NULL,NULL,NULL),(NULL,'MEX','Mexico City',489,68,NULL,NULL,NULL),(NULL,'MRD','Merida',490,68,NULL,NULL,NULL),(NULL,'PVR','Puerto Vallarta',491,68,NULL,NULL,NULL),(NULL,'RVM','Riviera Maya',492,68,NULL,NULL,NULL),(NULL,'ATT','Attard',493,69,NULL,NULL,NULL),(NULL,'BUB','Bugibba',494,69,NULL,NULL,NULL),(NULL,'GOL','Golden Bay',495,69,NULL,NULL,NULL),(NULL,'GOZ','Gozo',496,69,NULL,NULL,NULL),(NULL,'MEH','Mellieha',497,69,NULL,NULL,NULL),(NULL,'QAW','Qawra',498,69,NULL,NULL,NULL),(NULL,'SJL','St. Julians',499,69,NULL,NULL,NULL),(NULL,'SLM','Sliema',500,69,NULL,NULL,NULL),(NULL,'SPU','St. Pauls Bay',501,69,NULL,NULL,NULL),(NULL,'VLT','Valletta',502,69,NULL,NULL,NULL),(NULL,'CIS','Chisinau',503,70,NULL,NULL,NULL),(NULL,'MCA','Monte Carlo',504,71,NULL,NULL,NULL),(NULL,'BDV','Budva',505,72,NULL,NULL,NULL),(NULL,'HCG','Herceg Novi',506,72,NULL,NULL,NULL),(NULL,'MRU','Mauritius',507,73,NULL,NULL,NULL),(NULL,'IHP','Ipoh',508,74,NULL,NULL,NULL),(NULL,'KLP','Kuala Lumpur',509,74,NULL,NULL,NULL),(NULL,'KTK','Kota Kinabalu (Borneo)',510,74,NULL,NULL,NULL),(NULL,'LGK','Langkawi',511,74,NULL,NULL,NULL),(NULL,'MLK','Melaka',512,74,NULL,NULL,NULL),(NULL,'PNG','Penang',513,74,NULL,NULL,NULL),(NULL,'SDK','Sandakan (Borneo)',514,74,NULL,NULL,NULL),(NULL,'AMS','Amsterdam',515,75,NULL,NULL,NULL),(NULL,'DLF','Delft',516,75,NULL,NULL,NULL),(NULL,'EIN','Eindhoven',517,75,NULL,NULL,NULL),(NULL,'HAG','The Hague',518,75,NULL,NULL,NULL),(NULL,'HOO','Hoofddorp',519,75,NULL,NULL,NULL),(NULL,'LED','Leiden',520,75,NULL,NULL,NULL),(NULL,'MAA','Maastricht',521,75,NULL,NULL,NULL),(NULL,'RTH','Rotterdam',522,75,NULL,NULL,NULL),(NULL,'UTR','Utrecht',523,75,NULL,NULL,NULL),(NULL,'AUC','Auckland',524,76,NULL,NULL,NULL),(NULL,'BEJ','Bay of Islands ',525,76,NULL,NULL,NULL),(NULL,'CSR','Christchurch',526,76,NULL,NULL,NULL),(NULL,'DUI','Dunedin',527,76,NULL,NULL,NULL),(NULL,'QNT','Queenstown',528,76,NULL,NULL,NULL),(NULL,'RTR','Rotorua',529,76,NULL,NULL,NULL),(NULL,'TUO','Lake Taupo ',530,76,NULL,NULL,NULL),(NULL,'WLG','Wellington ',531,76,NULL,NULL,NULL),(NULL,'ALT','Alta',532,77,NULL,NULL,NULL),(NULL,'ALU','Alesund',533,77,NULL,NULL,NULL),(NULL,'ALX','Al',534,77,NULL,NULL,NULL),(NULL,'ARA','Arendal',535,77,NULL,NULL,NULL),(NULL,'ASG','Asgardstrand',536,77,NULL,NULL,NULL),(NULL,'BGO','Bergen',537,77,NULL,NULL,NULL),(NULL,'BNS','Bronnoysund',538,77,NULL,NULL,NULL),(NULL,'BOD','Bodo',539,77,NULL,NULL,NULL),(NULL,'GJO','Gjovik',540,77,NULL,NULL,NULL),(NULL,'HMM','Hammerfest',541,77,NULL,NULL,NULL),(NULL,'HMR','Hamar',542,77,NULL,NULL,NULL),(NULL,'HRS','Harstad',543,77,NULL,NULL,NULL),(NULL,'KRN','Kristiansand',544,77,NULL,NULL,NULL),(NULL,'MOL','Molde',545,77,NULL,NULL,NULL),(NULL,'NRS','Noresund ',546,77,NULL,NULL,NULL),(NULL,'OSL','Oslo',547,77,NULL,NULL,NULL),(NULL,'SAD','Sandnes',548,77,NULL,NULL,NULL),(NULL,'SKI','Skien',549,77,NULL,NULL,NULL),(NULL,'SKP','Skeikampen',550,77,NULL,NULL,NULL),(NULL,'STA','Stavanger',551,77,NULL,NULL,NULL),(NULL,'TOB','Tonsberg',552,77,NULL,NULL,NULL),(NULL,'TRH','Trondheim',553,77,NULL,NULL,NULL),(NULL,'TRM','Tromso',554,77,NULL,NULL,NULL),(NULL,'MCT','Muscat',555,78,NULL,NULL,NULL),(NULL,'GDK','Gdansk',556,79,NULL,NULL,NULL),(NULL,'GDY','Gdynia',557,79,NULL,NULL,NULL),(NULL,'KAT','Katowice',558,79,NULL,NULL,NULL),(NULL,'KRA','Krakow',559,79,NULL,NULL,NULL),(NULL,'LOD','Lodz',560,79,NULL,NULL,NULL),(NULL,'MDZ','Miedzyzdroje',561,79,NULL,NULL,NULL),(NULL,'POZ','Poznan',562,79,NULL,NULL,NULL),(NULL,'STP','Sopot',563,79,NULL,NULL,NULL),(NULL,'SZC','Szczecin',564,79,NULL,NULL,NULL),(NULL,'TPN','Torun',565,79,NULL,NULL,NULL),('Poland second largest City',NULL,'Warsaw',566,79,180,80,NULL),('Poland Capital\'s City',NULL,'Wroclaw',567,79,190,70,NULL),(NULL,'ALA','Algarve',568,80,NULL,NULL,NULL),(NULL,'AZO','Azores Islands',569,80,NULL,NULL,NULL),(NULL,'BRR','Braga',570,80,NULL,NULL,NULL),(NULL,'COI','Coimbra',571,80,NULL,NULL,NULL),(NULL,'CSC','Cascais',572,80,NULL,NULL,NULL),(NULL,'EST','Estoril',573,80,NULL,NULL,NULL),(NULL,'EVO','Evora',574,80,NULL,NULL,NULL),(NULL,'FAT','Fatima',575,80,NULL,NULL,NULL),(NULL,'LIS','Lisbon',576,80,NULL,NULL,NULL),(NULL,'MDI','Madeira',577,80,NULL,NULL,NULL),(NULL,'OBI','Obidos',578,80,NULL,NULL,NULL),(NULL,'POO','Porto',579,80,NULL,NULL,NULL),(NULL,'PXO','Porto Santo',580,80,NULL,NULL,NULL),(NULL,'SIA','Sintra',581,80,NULL,NULL,NULL),(NULL,'SIM','Sesimbra',582,80,NULL,NULL,NULL),(NULL,'SUB','Setubal',583,80,NULL,NULL,NULL),(NULL,'SJU','San Juan',584,81,NULL,NULL,NULL),(NULL,'DOH','Doha',585,82,NULL,NULL,NULL),(NULL,'BUC','Bucharest',586,83,NULL,NULL,NULL),(NULL,'CNA','Constanta',587,83,NULL,NULL,NULL),(NULL,'OAD','Oradea',588,83,NULL,NULL,NULL),(NULL,'SBU','Sibiu',589,83,NULL,NULL,NULL),(NULL,'TIM','Timisoara',590,83,NULL,NULL,NULL),(NULL,'EKA','Ekaterinburg',591,84,NULL,NULL,NULL),(NULL,'KAZ','Kazan',592,84,NULL,NULL,NULL),(NULL,'MOS','Moscow',593,84,NULL,NULL,NULL),(NULL,'SOC','Sochi',594,84,NULL,NULL,NULL),(NULL,'STB','St. Petersburg',595,84,NULL,NULL,NULL),(NULL,'VDK','Vladivostok',596,84,NULL,NULL,NULL),(NULL,'JED','Jeddah',597,85,NULL,NULL,NULL),(NULL,'BGD','Belgrade',598,86,NULL,NULL,NULL),(NULL,'SIN','Singapore',599,87,NULL,NULL,NULL),(NULL,'BRV','Bratislava',600,88,NULL,NULL,NULL),(NULL,'VYS','High Tatras',601,88,NULL,NULL,NULL),(NULL,'LBH','Lake Bohinj',602,89,NULL,NULL,NULL),(NULL,'LJJ','Ljubljana',603,89,NULL,NULL,NULL),(NULL,'PZZ','Portoroz',604,89,NULL,NULL,NULL),(NULL,'ALI','Alicante',605,7,NULL,NULL,NULL),(NULL,'ALR','Almeria',606,7,NULL,NULL,NULL),(NULL,'AVS','Aviles',607,7,NULL,NULL,NULL),(NULL,'BAD','Badajoz',608,7,NULL,NULL,NULL),(NULL,'BCN','Barcelona',609,7,NULL,NULL,NULL),(NULL,'BIO','Bilbao',610,7,NULL,NULL,NULL),(NULL,'BND','Benidorm',611,7,NULL,NULL,NULL),(NULL,'BUR','Burgos',612,7,NULL,NULL,NULL),(NULL,'CAC','Caceres',613,7,NULL,NULL,NULL),(NULL,'CAZ','Cadiz',614,7,NULL,NULL,NULL),(NULL,'CDL','Cadiz - Costa de la Luz',615,7,NULL,NULL,NULL),(NULL,'CIU','Ciudad Real',616,7,NULL,NULL,NULL),(NULL,'CST','Castellon',617,7,NULL,NULL,NULL),(NULL,'FUE','Fuerteventura',618,7,NULL,NULL,NULL),(NULL,'GIJ','Gijon',619,7,NULL,NULL,NULL),(NULL,'GIR','Girona',620,7,NULL,NULL,NULL),(NULL,'GNC','Gran Canaria',621,7,NULL,NULL,NULL),(NULL,'GRX','Granada',622,7,NULL,NULL,NULL),(NULL,'HSC','Huesca',623,7,NULL,NULL,NULL),(NULL,'HUE','Huelva',624,7,NULL,NULL,NULL),(NULL,'IBZ','Ibiza',625,7,NULL,NULL,NULL),(NULL,'JEZ','Jerez de la Frontera',626,7,NULL,NULL,NULL),(NULL,'LAC','La Coruna',627,7,NULL,NULL,NULL),(NULL,'LAN','Lanzarote',628,7,NULL,NULL,NULL),(NULL,'LEO','Leon',629,7,NULL,NULL,NULL),(NULL,'LLE','Lerida',630,7,NULL,NULL,NULL),(NULL,'LLO','Lloret De Mar',631,7,NULL,NULL,NULL),(NULL,'MAD','Madrid',632,7,NULL,NULL,NULL),(NULL,'MAJ','Majorca',633,7,NULL,NULL,NULL),(NULL,'MAL','Malaga',634,7,NULL,NULL,NULL),(NULL,'MBL','Marbella',635,7,NULL,NULL,NULL),(NULL,'MIN','Menorca',636,7,NULL,NULL,NULL),(NULL,'MRC','Murcia',637,7,NULL,NULL,NULL),(NULL,'ODB','Cordoba',638,7,NULL,NULL,NULL),(NULL,'OVI','Oviedo',639,7,NULL,NULL,NULL),(NULL,'PAL','La Palma',640,7,NULL,NULL,NULL),(NULL,'PDA','Platja d\'Aro',641,7,NULL,NULL,NULL),(NULL,'PIN','Pineda de Mar',642,7,NULL,NULL,NULL),(NULL,'PMP','Pamplona',643,7,NULL,NULL,NULL),(NULL,'PVD','Pontevedra',644,7,NULL,NULL,NULL),(NULL,'RJL','Logrono',645,7,NULL,NULL,NULL),(NULL,'SAA','Salamanca',646,7,NULL,NULL,NULL),(NULL,'SDC','Santiago de Compostela',647,7,NULL,NULL,NULL),(NULL,'SDE','Sabadell',648,7,NULL,NULL,NULL),(NULL,'SIT','Sitges',649,7,NULL,NULL,NULL),(NULL,'SLU','Salou',650,7,NULL,NULL,NULL),(NULL,'SSB','San Sebastian',651,7,NULL,NULL,NULL),(NULL,'STD','Santander',652,7,NULL,NULL,NULL),(NULL,'SUS','Santa Susana',653,7,NULL,NULL,NULL),(NULL,'SVQ','Seville',654,7,NULL,NULL,NULL),(NULL,'TFE','Tenerife',655,7,NULL,NULL,NULL),(NULL,'TGG','Tarragona',656,7,NULL,NULL,NULL),(NULL,'TOL','Toledo',657,7,NULL,NULL,NULL),(NULL,'TOR','Torremolinos',658,7,NULL,NULL,NULL),(NULL,'TOS','Tossa de Mar',659,7,NULL,NULL,NULL),(NULL,'VAL','Valencia',660,7,NULL,NULL,NULL),(NULL,'VIR','Vitoria',661,7,NULL,NULL,NULL),(NULL,'VLD','Valladolid',662,7,NULL,NULL,NULL),(NULL,'ZAZ','Zaragoza',663,7,NULL,NULL,NULL),(NULL,'ZMO','Zamora',664,7,NULL,NULL,NULL),(NULL,'GOT','Gothenburg',665,10,NULL,NULL,NULL),(NULL,'HLG','Helsingborg',666,10,NULL,NULL,NULL),(NULL,'JON','Jonkoping',667,10,NULL,NULL,NULL),(NULL,'KAL','Kalmar',668,10,NULL,NULL,NULL),(NULL,'KRL','Karlstad',669,10,NULL,NULL,NULL),(NULL,'LUL','Lulea',670,10,NULL,NULL,NULL),(NULL,'MMX','Malmo',671,10,NULL,NULL,NULL),(NULL,'NKK','Norrkoping',672,10,NULL,NULL,NULL),(NULL,'ORE','Orebro',673,10,NULL,NULL,NULL),(NULL,'STO','Stockholm',674,10,NULL,NULL,NULL),(NULL,'UME','Umea',675,10,NULL,NULL,NULL),(NULL,'UPP','Uppsala',676,10,NULL,NULL,NULL),(NULL,'ARO','Arosa',677,92,NULL,NULL,NULL),(NULL,'BNE','Bern',678,92,NULL,NULL,NULL),(NULL,'BSL','Basel',679,92,NULL,NULL,NULL),(NULL,'DAV','Davos',680,92,NULL,NULL,NULL),(NULL,'ENG','Engelberg',681,92,NULL,NULL,NULL),(NULL,'FRB','Fribourg',682,92,NULL,NULL,NULL),(NULL,'GRD','Grindelwald',683,92,NULL,NULL,NULL),(NULL,'GTD','Gstaad',684,92,NULL,NULL,NULL),(NULL,'GVA','Geneva',685,92,NULL,NULL,NULL),(NULL,'ITK','Interlaken',686,92,NULL,NULL,NULL),(NULL,'LAU','Lausanne',687,92,NULL,NULL,NULL),(NULL,'LCR','Locarno',688,92,NULL,NULL,NULL),(NULL,'LGN','Lugano',689,92,NULL,NULL,NULL),(NULL,'LKB','Leukerbad',690,92,NULL,NULL,NULL),(NULL,'LUC','Lucerne',691,92,NULL,NULL,NULL),(NULL,'MTX','Montreux',692,92,NULL,NULL,NULL),(NULL,'SFE','Saas-Fee',693,92,NULL,NULL,NULL),(NULL,'SGA','St. Gallen',694,92,NULL,NULL,NULL),(NULL,'STM','St Moritz',695,92,NULL,NULL,NULL),(NULL,'WEN','Wengen',696,92,NULL,NULL,NULL),(NULL,'ZER','Zermatt',697,92,NULL,NULL,NULL),(NULL,'ZRH','Zurich',698,92,NULL,NULL,NULL),(NULL,'BKK','Bangkok',699,93,NULL,NULL,NULL),(NULL,'CNX','Chiang Mai',700,93,NULL,NULL,NULL),(NULL,'CRA','Chiang Rai',701,93,NULL,NULL,NULL),(NULL,'HKT','Phuket',702,93,NULL,NULL,NULL),(NULL,'HUA','Hua Hin',703,93,NULL,NULL,NULL),(NULL,'KBI','Krabi',704,93,NULL,NULL,NULL),(NULL,'KOC','Koh Chang',705,93,NULL,NULL,NULL),(NULL,'KOH','Koh Samui',706,93,NULL,NULL,NULL),(NULL,'KPG','Koh Phangan',707,93,NULL,NULL,NULL),(NULL,'PTY','Pattaya',708,93,NULL,NULL,NULL),(NULL,'ADA','Adana',709,94,NULL,NULL,NULL),(NULL,'ANK','Ankara',710,94,NULL,NULL,NULL),(NULL,'ATK','Altinkum',711,94,NULL,NULL,NULL),(NULL,'ATY','Antalya',712,94,NULL,NULL,NULL),(NULL,'BDR','Bodrum',713,94,NULL,NULL,NULL),(NULL,'BTZ','Bursa',714,94,NULL,NULL,NULL),(NULL,'CKK','Canakkale',715,94,NULL,NULL,NULL),(NULL,'CPD','Cappadocia',716,94,NULL,NULL,NULL),(NULL,'DLM','Dalaman',717,94,NULL,NULL,NULL),(NULL,'DNZ','Denizli',718,94,NULL,NULL,NULL),(NULL,'FET','Fethiye',719,94,NULL,NULL,NULL),(NULL,'GZP','Gaziantep',720,94,NULL,NULL,NULL),(NULL,'HYA','Hatay',721,94,NULL,NULL,NULL),(NULL,'IST','Istanbul',722,94,NULL,NULL,NULL),(NULL,'IZR','Izmir',723,94,NULL,NULL,NULL),(NULL,'KSD','Kusadasi',724,94,NULL,NULL,NULL),(NULL,'KUY','Kutahya',725,94,NULL,NULL,NULL),(NULL,'KYO','Konya',726,94,NULL,NULL,NULL),(NULL,'MIS','Marmaris',727,94,NULL,NULL,NULL),(NULL,'TPE','Taipei',728,95,NULL,NULL,NULL),(NULL,'ABD','Aberdeen',729,8,NULL,NULL,NULL),(NULL,'ABE','Aberfoyle',730,8,NULL,NULL,NULL),(NULL,'ARU','Arundel',731,8,NULL,NULL,NULL),(NULL,'ASH','Ashford',732,8,NULL,NULL,NULL),(NULL,'AST','Ascot',733,8,NULL,NULL,NULL),(NULL,'AVM','Aviemore',734,8,NULL,NULL,NULL),(NULL,'AYB','Aylesbury',735,8,NULL,NULL,NULL),(NULL,'AYR','Ayr',736,8,NULL,NULL,NULL),(NULL,'BAN','Banbury',737,8,NULL,NULL,NULL),(NULL,'BAS','Basingstoke',738,8,NULL,NULL,NULL),(NULL,'BAT','Bath',739,8,NULL,NULL,NULL),(NULL,'BEL','Belfast',740,8,NULL,NULL,NULL),(NULL,'BFD','Bedford',741,8,NULL,NULL,NULL),(NULL,'BIR','Birmingham',742,8,NULL,NULL,NULL),(NULL,'BKN','Bracknell',743,8,NULL,NULL,NULL),(NULL,'BLA','Blackpool',744,8,NULL,NULL,NULL),(NULL,'BLB','Blackburn',745,8,NULL,NULL,NULL),(NULL,'BOH','Bournemouth',746,8,NULL,NULL,NULL),(NULL,'BOL','Bolton',747,8,NULL,NULL,NULL),(NULL,'BRD','Bradford',748,8,NULL,NULL,NULL),(NULL,'BRI','Brighton',749,8,NULL,NULL,NULL),(NULL,'BRS','Bristol',750,8,NULL,NULL,NULL),(NULL,'BSD','Basildon',751,8,NULL,NULL,NULL),(NULL,'BUT','Burton-Upon-Trent',752,8,NULL,NULL,NULL),(NULL,'BUX','Buxton',753,8,NULL,NULL,NULL),(NULL,'BYG','Ballygally',754,8,NULL,NULL,NULL),(NULL,'CAM','Cambridge',755,8,NULL,NULL,NULL),(NULL,'CDF','Cardiff',756,8,NULL,NULL,NULL),(NULL,'CHE','Chester',757,8,NULL,NULL,NULL),(NULL,'CHM','Chatham',758,8,NULL,NULL,NULL),(NULL,'CLT','Cheltenham',759,8,NULL,NULL,NULL),(NULL,'COV','Coventry',760,8,NULL,NULL,NULL),(NULL,'CTW','Cotswolds',761,8,NULL,NULL,NULL),(NULL,'CTY','Canterbury',762,8,NULL,NULL,NULL),(NULL,'DER','Derby',763,8,NULL,NULL,NULL),(NULL,'DKG','Dorking',764,8,NULL,NULL,NULL),(NULL,'DOV','Dover',765,8,NULL,NULL,NULL),(NULL,'DUN','Dundee',766,8,NULL,NULL,NULL),(NULL,'DUR','Durham',767,8,NULL,NULL,NULL),(NULL,'DVY','Daventry',768,8,NULL,NULL,NULL),(NULL,'EAB','Eastbourne',769,8,NULL,NULL,NULL),(NULL,'EDI','Edinburgh',770,8,NULL,NULL,NULL),(NULL,'EKB','East Kilbride',771,8,NULL,NULL,NULL),(NULL,'ENI','Enniskillen',772,8,NULL,NULL,NULL),(NULL,'EXE','Exeter',773,8,NULL,NULL,NULL),(NULL,'FAB','Farnborough',774,8,NULL,NULL,NULL),(NULL,'FAK','Falkirk',775,8,NULL,NULL,NULL),(NULL,'FLK','Folkestone',777,8,NULL,NULL,NULL),(NULL,'FRN','Farnham',778,8,NULL,NULL,NULL),(NULL,'FTW','Fort William',779,8,NULL,NULL,NULL),(NULL,'GLA','Glasgow',780,8,NULL,NULL,NULL),(NULL,'GLO','Gloucester',781,8,NULL,NULL,NULL),(NULL,'GUI','Guildford',782,8,NULL,NULL,NULL),(NULL,'HAR','Harrogate',783,8,NULL,NULL,NULL),(NULL,'HAT','Hatfield',784,8,NULL,NULL,NULL),(NULL,'HGW','High Wycombe',785,8,NULL,NULL,NULL),(NULL,'HHE','Hemel Hempstead',786,8,NULL,NULL,NULL),(NULL,'HIN','Hinckley',787,8,NULL,NULL,NULL),(NULL,'HLE','Hale',788,8,NULL,NULL,NULL),(NULL,'HUL','Hull',789,8,NULL,NULL,NULL),(NULL,'HYD','Haydock',790,8,NULL,NULL,NULL),(NULL,'INV','Inverness',791,8,NULL,NULL,NULL),(NULL,'IOM','Isle of Man',792,8,NULL,NULL,NULL),(NULL,'IPS','Ipswich',793,8,NULL,NULL,NULL),(NULL,'IRR','Isle of Arran',794,8,NULL,NULL,NULL),(NULL,'JES','Jersey',795,8,NULL,NULL,NULL),(NULL,'KID','Kidderminster',796,8,NULL,NULL,NULL),(NULL,'LCA','Lancaster',797,8,NULL,NULL,NULL),(NULL,'LDN','Londonderry',798,8,NULL,NULL,NULL),(NULL,'LDS','Leeds',799,8,NULL,NULL,NULL),(NULL,'LEI','Leicester',800,8,NULL,NULL,NULL),(NULL,'LGW','London Gatwick Airport',801,8,NULL,NULL,NULL),(NULL,'LHR','London Heathrow Airport',802,8,NULL,NULL,NULL),(NULL,'LIN','Lincoln',803,8,NULL,NULL,NULL),(NULL,'LIV','Liverpool',804,8,NULL,NULL,NULL),(NULL,'LKD','Lake District',805,8,NULL,NULL,NULL),(NULL,'LLA','Llandudno',806,8,NULL,NULL,NULL),(NULL,'LMT','Lymington',807,8,NULL,NULL,NULL),(NULL,'LOC','Lochinver',808,8,NULL,NULL,NULL),(NULL,'LON','London',809,8,NULL,NULL,NULL),(NULL,'LUT','Luton',810,8,NULL,NULL,NULL),(NULL,'LVS','Livingston',811,8,NULL,NULL,NULL),(NULL,'MAI','Maidstone',812,8,NULL,NULL,NULL),(NULL,'MAN','Manchester',813,8,NULL,NULL,NULL),(NULL,'MCB','Morecambe',814,8,NULL,NULL,NULL),(NULL,'MCC','Macclesfield',815,8,NULL,NULL,NULL),(NULL,'MDD','Middlesbrough',816,8,NULL,NULL,NULL),(NULL,'MKB','Market Bosworth',817,8,NULL,NULL,NULL),(NULL,'MKE','Milton Keynes',818,8,NULL,NULL,NULL),(NULL,'NBY','Newbury',819,8,NULL,NULL,NULL),(NULL,'NEP','Newport (Wales)',820,8,NULL,NULL,NULL),(NULL,'NEQ','Newquay',821,8,NULL,NULL,NULL),(NULL,'NEW','Newcastle-Upon-Tyne',822,8,NULL,NULL,NULL),(NULL,'NHM','Northampton',823,8,NULL,NULL,NULL),(NULL,'NOT','Nottingham',824,8,NULL,NULL,NULL),(NULL,'NRC','Norwich',825,8,NULL,NULL,NULL),(NULL,'OXF','Oxford',826,8,NULL,NULL,NULL),(NULL,'PEE','Peebles',827,8,NULL,NULL,NULL),(NULL,'PLY','Plymouth',828,8,NULL,NULL,NULL),(NULL,'PRT','Portsmouth',829,8,NULL,NULL,NULL),(NULL,'PST','Preston',830,8,NULL,NULL,NULL),(NULL,'RAN','Rannoch Moor',832,8,NULL,NULL,NULL),(NULL,'RCH','Rochdale',833,8,NULL,NULL,NULL),(NULL,'RDG','Reading',834,8,NULL,NULL,NULL),(NULL,'SAB','St Albans',835,8,NULL,NULL,NULL),(NULL,'SAL','Salisbury',836,8,NULL,NULL,NULL),(NULL,'SAW','St Andrews',837,8,NULL,NULL,NULL),(NULL,'SBH','Scarborough',838,8,NULL,NULL,NULL),(NULL,'SHF','Sheffield',839,8,NULL,NULL,NULL),(NULL,'SNT','Staines',840,8,NULL,NULL,NULL),(NULL,'SOT','Stoke-on-Trent',841,8,NULL,NULL,NULL),(NULL,'SPT','Southport',842,8,NULL,NULL,NULL),(NULL,'STC','Stockport',843,8,NULL,NULL,NULL),(NULL,'STE','London Stansted Airport',844,8,NULL,NULL,NULL),(NULL,'STF','Stratford-upon-Avon',845,8,NULL,NULL,NULL),(NULL,'STL','Stirling',846,8,NULL,NULL,NULL),(NULL,'STN','Southampton',847,8,NULL,NULL,NULL),(NULL,'STV','Stevenage',848,8,NULL,NULL,NULL),(NULL,'SWI','Swindon',849,8,NULL,NULL,NULL),(NULL,'SWS','Swansea',850,8,NULL,NULL,NULL),(NULL,'TAU','Taunton',851,8,NULL,NULL,NULL),(NULL,'TQY','Torquay',852,8,NULL,NULL,NULL),(NULL,'TRN','Troon',853,8,NULL,NULL,NULL),(NULL,'TUN','Tunbridge Wells',854,8,NULL,NULL,NULL),(NULL,'TWK','Tewkesbury',855,8,NULL,NULL,NULL),(NULL,'WCH','Winchester',856,8,NULL,NULL,NULL),(NULL,'WCK','Warwick',857,8,NULL,NULL,NULL),(NULL,'WHC','Whitchurch',858,8,NULL,NULL,NULL),(NULL,'WIG','Wigan',859,8,NULL,NULL,NULL),(NULL,'WIN','Windsor',860,8,NULL,NULL,NULL),(NULL,'WKN','Woking',861,8,NULL,NULL,NULL),(NULL,'WOL','Wolverhampton',862,8,NULL,NULL,NULL),(NULL,'WRR','Warrington',863,8,NULL,NULL,NULL),(NULL,'WTF','Watford',864,8,NULL,NULL,NULL),(NULL,'YOR','York',865,8,NULL,NULL,NULL),(NULL,'DSK','Donetsk',866,97,NULL,NULL,NULL),(NULL,'KHV','Kharkiv',867,97,NULL,NULL,NULL),(NULL,'KIV','Kiev',868,97,NULL,NULL,NULL),(NULL,'LVI','Lviv',869,97,NULL,NULL,NULL),(NULL,'ODS','Odessa',870,97,NULL,NULL,NULL),(NULL,'MVD','Montevideo',871,98,NULL,NULL,NULL),(NULL,'BOS','Boston ',872,3,NULL,NULL,NULL),(NULL,'CHI','Chicago ',873,3,NULL,NULL,NULL),(NULL,'CWT','Clearwater ',874,3,NULL,NULL,NULL),(NULL,'DCA','Washington DC',875,3,NULL,NULL,NULL),(NULL,'EYW','Florida Keys ',876,3,NULL,NULL,NULL),(NULL,'FLL','Fort Lauderdale ',877,3,NULL,NULL,NULL),(NULL,'HNL','Honolulu ',878,3,NULL,NULL,NULL),(NULL,'HUR','Huntington Beach ',879,3,NULL,NULL,NULL),(NULL,'JCY','Jersey City ',880,3,NULL,NULL,NULL),(NULL,'LAS','Las Vegas ',881,3,NULL,NULL,NULL),(NULL,'LAX','Los Angeles ',882,3,NULL,NULL,NULL),(NULL,'LGB','Long Beach ',883,3,NULL,NULL,NULL),(NULL,'MAU','Maui ',884,3,NULL,NULL,NULL),(NULL,'MIA','Miami ',885,3,NULL,NULL,NULL),(NULL,'NBG','New Orleans ',886,3,NULL,NULL,NULL),(NULL,'NPB','Newport Beach ',887,3,NULL,NULL,NULL),(NULL,'NPL','Naples ',888,3,NULL,NULL,NULL),(NULL,'NYC','New York ',889,3,NULL,NULL,NULL),(NULL,'ORO','Orlando ',890,3,NULL,NULL,NULL),(NULL,'PHL','Philadelphia ',891,3,NULL,NULL,NULL),(NULL,'SCJ','San Jose ',892,3,NULL,NULL,NULL),(NULL,'SDU','San Diego ',893,3,NULL,NULL,NULL),(NULL,'SFO','San Francisco ',894,3,NULL,NULL,NULL),(NULL,'SPR','St Petersburg ',895,3,NULL,NULL,NULL),(NULL,'SST','Seattle ',896,3,NULL,NULL,NULL),(NULL,'TPA','Tampa ',897,3,NULL,NULL,NULL),(NULL,'WTY','West Point ',898,3,NULL,NULL,NULL),(NULL,'DAD','Da Nang',899,101,NULL,NULL,NULL),(NULL,'HNI','Hanoi',900,101,NULL,NULL,NULL),(NULL,'SGN','Ho Chi Minh ',901,101,NULL,NULL,NULL),(NULL,'CPT','Cape Town',902,102,NULL,NULL,NULL),(NULL,'JHB','Johannesburg',903,102,NULL,NULL,NULL),('Delhi NCR','NDA','Noida',908,1,NULL,NULL,NULL),(NULL,NULL,'Adoni',1046,1,NULL,NULL,NULL),(NULL,NULL,'Ahmednagar',1047,1,NULL,NULL,NULL),(NULL,NULL,'Ajmer',1048,1,NULL,NULL,NULL),(NULL,NULL,'Akola',1049,1,NULL,NULL,NULL),(NULL,NULL,'Alchi',1050,1,NULL,NULL,NULL),(NULL,NULL,'Alibaugh',1051,1,NULL,NULL,NULL),(NULL,NULL,'Allahabad',1052,1,NULL,NULL,NULL),(NULL,NULL,'Alleppey',1053,1,NULL,NULL,NULL),(NULL,NULL,'Almora',1054,1,NULL,NULL,NULL),(NULL,NULL,'Alsisar',1055,1,NULL,NULL,NULL),(NULL,NULL,'Alwar',1056,1,NULL,NULL,NULL),(NULL,NULL,'Amla',1057,1,NULL,NULL,NULL),(NULL,NULL,'Amritsar',1058,1,NULL,NULL,NULL),(NULL,NULL,'Anand',1059,1,NULL,NULL,NULL),(NULL,NULL,'Auli',1060,1,NULL,NULL,NULL),(NULL,NULL,'Aurangabad',1061,1,NULL,NULL,NULL),(NULL,NULL,'Bambora',1062,1,NULL,NULL,NULL),(NULL,NULL,'Badami',1063,1,NULL,NULL,NULL),(NULL,NULL,'Badrinath',1064,1,NULL,NULL,NULL),(NULL,NULL,'Balrampur',1065,1,NULL,NULL,NULL),(NULL,NULL,'Bandhavgarh',1066,1,NULL,NULL,NULL),(NULL,NULL,'Bandipur',1067,1,NULL,NULL,NULL),(NULL,NULL,'Bassi',1068,1,NULL,NULL,NULL),(NULL,NULL,'Betalghat',1069,1,NULL,NULL,NULL),(NULL,NULL,'Bhalukpong',1070,1,NULL,NULL,NULL),(NULL,NULL,'Bharatpur',1071,1,NULL,NULL,NULL),(NULL,NULL,'Bhavnagar',1072,1,NULL,NULL,NULL),(NULL,NULL,'Bhimtal',1073,1,NULL,NULL,NULL),(NULL,NULL,'Bhopal',1074,1,NULL,NULL,NULL),('City of Temples','','Bhubaneshwar',1075,1,NULL,NULL,NULL),(NULL,NULL,'Bhuj',1076,1,NULL,NULL,NULL),(NULL,NULL,'Bikaner',1077,1,NULL,NULL,NULL),(NULL,NULL,'Bomdila',1078,1,NULL,NULL,NULL),(NULL,NULL,'Binsar',1079,1,NULL,NULL,NULL),(NULL,NULL,'Calicut',1080,1,NULL,NULL,NULL),(NULL,NULL,'Chail',1081,1,NULL,NULL,NULL),(NULL,NULL,'Chalsa',1082,1,NULL,NULL,NULL),(NULL,NULL,'Chamba',1083,1,NULL,NULL,NULL),('Capital of Punjab and Hariyana',NULL,'Chandigarh',1084,1,NULL,NULL,NULL),(NULL,NULL,'Chickmagalur',1085,1,NULL,NULL,NULL),(NULL,NULL,'Chiplun',1086,1,NULL,NULL,NULL),(NULL,NULL,'Chittorgarh',1087,1,NULL,NULL,NULL),('Cochi','','Cochine',1088,1,NULL,NULL,NULL),(NULL,NULL,'Coimbatore',1089,1,NULL,NULL,NULL),(NULL,NULL,'Coonoor',1090,1,NULL,NULL,NULL),('Coorg City.','','Coorg',1091,1,NULL,NULL,NULL),(NULL,NULL,'Corbett',1092,1,NULL,NULL,NULL),(NULL,NULL,'Cuddalore',1093,1,NULL,NULL,NULL),(NULL,NULL,'Dalhousie',1094,1,NULL,NULL,NULL),(NULL,NULL,'Daman',1095,1,NULL,NULL,NULL),(NULL,NULL,'Dandeli',1096,1,NULL,NULL,NULL),(NULL,NULL,'Darjeeling',1097,1,NULL,NULL,NULL),(NULL,NULL,'Dausa',1098,1,NULL,NULL,NULL),(NULL,NULL,'Dehradun',1099,1,NULL,NULL,NULL),(NULL,NULL,'Deogarh',1100,1,NULL,NULL,NULL),(NULL,NULL,'Deshkit',1101,1,NULL,NULL,NULL),(NULL,NULL,'Dhar',1102,1,NULL,NULL,NULL),(NULL,NULL,'Dharamshala',1103,1,NULL,NULL,NULL),(NULL,NULL,'Dibrugarh',1104,1,NULL,NULL,NULL),(NULL,NULL,'Diu',1105,1,NULL,NULL,NULL),(NULL,NULL,'Dooars',1106,1,NULL,NULL,NULL),(NULL,NULL,'Dungarpur',1107,1,NULL,NULL,NULL),(NULL,NULL,'Durgapur',1108,1,NULL,NULL,NULL),(NULL,NULL,'Dwarka',1109,1,NULL,NULL,NULL),(NULL,NULL,'Faridabad',1110,1,NULL,NULL,NULL),(NULL,NULL,'Gandhinagar',1111,1,NULL,NULL,NULL),(NULL,NULL,'Gangotri',1112,1,NULL,NULL,NULL),(NULL,NULL,'Gangtok',1113,1,NULL,NULL,NULL),(NULL,NULL,'Ganpatipule',1114,1,NULL,NULL,NULL),(NULL,NULL,'Garhmukteshwar',1115,1,NULL,NULL,NULL),(NULL,NULL,'Gaya',1116,1,NULL,NULL,NULL),(NULL,NULL,'Ghaziabad',1117,1,NULL,NULL,NULL),(NULL,NULL,'Gokarna',1118,1,NULL,NULL,NULL),(NULL,NULL,'Gondal',1119,1,NULL,NULL,NULL),(NULL,NULL,'Gopalpur',1120,1,NULL,NULL,NULL),(NULL,NULL,'Gulmarg',1121,1,NULL,NULL,NULL),(NULL,NULL,'Guruvayoor',1123,1,NULL,NULL,NULL),(NULL,NULL,'Guwahati',1124,1,NULL,NULL,NULL),(NULL,NULL,'Gwalior',1125,1,NULL,NULL,NULL),(NULL,NULL,'Hansi',1126,1,NULL,NULL,NULL),(NULL,NULL,'Haridwar',1127,1,NULL,NULL,NULL),(NULL,NULL,'Hassan',1128,1,NULL,NULL,NULL),(NULL,NULL,'Idukki',1129,1,NULL,NULL,NULL),(NULL,NULL,'Imphal',1130,1,NULL,NULL,NULL),(NULL,NULL,'Indore',1131,1,NULL,NULL,NULL),(NULL,NULL,'Jabalpur',1132,1,NULL,NULL,NULL),(NULL,NULL,'Jaisalmer',1133,1,NULL,NULL,NULL),(NULL,NULL,'Jaisamand',1134,1,NULL,NULL,NULL),(NULL,NULL,'Jalandhar',1135,1,NULL,NULL,NULL),(NULL,NULL,'Jammu',1136,1,NULL,NULL,NULL),(NULL,NULL,'Jamnagar',1137,1,NULL,NULL,NULL),(NULL,NULL,'Jamshedpur',1138,1,NULL,NULL,NULL),(NULL,NULL,'Jhansi',1139,1,NULL,NULL,NULL),(NULL,NULL,'Jodhpur',1140,1,NULL,NULL,NULL),(NULL,NULL,'Jorhat',1141,1,NULL,NULL,NULL),(NULL,NULL,'Junagadh',1142,1,NULL,NULL,NULL),(NULL,NULL,'Kabini',1143,1,NULL,NULL,NULL),(NULL,NULL,'Kalimpong',1144,1,NULL,NULL,NULL),(NULL,NULL,'Kanchipuram',1145,1,NULL,NULL,NULL),(NULL,NULL,'Kanha',1146,1,NULL,NULL,NULL),(NULL,NULL,'Kanyakumari',1147,1,NULL,NULL,NULL),(NULL,NULL,'Kanpur',1148,1,NULL,NULL,NULL),(NULL,NULL,'Kasauli',1149,1,NULL,NULL,NULL),(NULL,NULL,'Karauli',1150,1,NULL,NULL,NULL),(NULL,NULL,'Kargil',1151,1,NULL,NULL,NULL),(NULL,NULL,'Katra',1152,1,NULL,NULL,NULL),(NULL,NULL,'Kasauni',1153,1,NULL,NULL,NULL),(NULL,NULL,'Kaziranga',1154,1,NULL,NULL,NULL),(NULL,NULL,'Kedarnath',1155,1,NULL,NULL,NULL),(NULL,NULL,'Khajjiar',1156,1,NULL,NULL,NULL),(NULL,NULL,'Khajuraho',1157,1,NULL,NULL,NULL),(NULL,NULL,'Khandala',1158,1,NULL,NULL,NULL),(NULL,NULL,'Khimsar',1159,1,NULL,NULL,NULL),(NULL,NULL,'Khejarla',1160,1,NULL,NULL,NULL),(NULL,NULL,'Kodaikanal',1161,1,NULL,NULL,NULL),(NULL,NULL,'Kohima',1162,1,NULL,NULL,NULL),(NULL,NULL,'Kolhapur',1163,1,NULL,NULL,NULL),(NULL,NULL,'Kollam',1164,1,NULL,NULL,NULL),(NULL,NULL,'Kosi',1165,1,NULL,NULL,NULL),(NULL,NULL,'Kota',1166,1,NULL,NULL,NULL),(NULL,NULL,'Kottayam',1167,1,NULL,NULL,NULL),(NULL,NULL,'Kovalam',1168,1,NULL,NULL,NULL),(NULL,NULL,'Kufri',1169,1,NULL,NULL,NULL),(NULL,NULL,'Kullu',1170,1,NULL,NULL,NULL),(NULL,NULL,'Kumarakom',1171,1,NULL,NULL,NULL),(NULL,NULL,'Kumbalgarh',1172,1,NULL,NULL,NULL),(NULL,NULL,'Kushinagar',1173,1,NULL,NULL,NULL),(NULL,NULL,'Kurnool',1174,1,NULL,NULL,NULL),(NULL,NULL,'Lachung',1175,1,NULL,NULL,NULL),(NULL,NULL,'Lakshadweep',1176,1,NULL,NULL,NULL),(NULL,NULL,'Leh',1177,1,NULL,NULL,NULL),(NULL,NULL,'Lonavala',1178,1,NULL,NULL,NULL),(NULL,NULL,'Lucknow',1179,1,NULL,NULL,NULL),(NULL,NULL,'Ludhiana',1180,1,NULL,NULL,NULL),(NULL,NULL,'Madhumalai',1181,1,NULL,NULL,NULL),(NULL,NULL,'Madurai',1182,1,NULL,NULL,NULL),(NULL,NULL,'Mahabaleshwar',1183,1,NULL,NULL,NULL),(NULL,NULL,'Mahalbalipuram',1184,1,NULL,NULL,NULL),(NULL,NULL,'Mamallapuram',1185,1,NULL,NULL,NULL),(NULL,NULL,'Manali',1186,1,NULL,NULL,NULL),(NULL,NULL,'Mandawa',1187,1,NULL,NULL,NULL),(NULL,NULL,'Mandi',1188,1,NULL,NULL,NULL),(NULL,NULL,'Mandu',1189,1,NULL,NULL,NULL),(NULL,NULL,'Mandvi',1190,1,NULL,NULL,NULL),(NULL,NULL,'Manesar',1191,1,NULL,NULL,NULL),(NULL,NULL,'Marchula',1192,1,NULL,NULL,NULL),(NULL,NULL,'Mangalore',1193,1,NULL,NULL,NULL),(NULL,NULL,'Manvar',1194,1,NULL,NULL,NULL),(NULL,NULL,'Mashobra',1195,1,NULL,NULL,NULL),(NULL,NULL,'Matheran',1196,1,NULL,NULL,NULL),(NULL,NULL,'Mathura',1197,1,NULL,NULL,NULL),(NULL,NULL,'Mehsana',1198,1,NULL,NULL,NULL),(NULL,NULL,'Mohali',1199,1,NULL,NULL,NULL),(NULL,NULL,'Mount Abu',1200,1,NULL,NULL,NULL),(NULL,NULL,'Mukteshwar',1201,1,NULL,NULL,NULL),(NULL,NULL,'Munnar',1202,1,NULL,NULL,NULL),(NULL,NULL,'Murud',1203,1,NULL,NULL,NULL),(NULL,NULL,'Mussoorie',1204,1,NULL,NULL,NULL),(NULL,NULL,'Mysore',1205,1,NULL,NULL,NULL),(NULL,NULL,'Nadukani',1206,1,NULL,NULL,NULL),(NULL,NULL,'Nagarhole',1207,1,NULL,NULL,NULL),(NULL,NULL,'Nagarjunsagar',1208,1,NULL,NULL,NULL),(NULL,NULL,'Nagaur',1209,1,NULL,NULL,NULL),(NULL,NULL,'Nainital',1210,1,NULL,NULL,NULL),(NULL,NULL,'Nalagarh',1211,1,NULL,NULL,NULL),(NULL,NULL,'Nashik',1212,1,NULL,NULL,NULL),(NULL,NULL,'Nathdwara',1213,1,NULL,NULL,NULL),(NULL,NULL,'Neemrana',1214,1,NULL,NULL,NULL),(NULL,NULL,'Ooty',1215,1,NULL,NULL,NULL),(NULL,NULL,'Orchha',1216,1,NULL,NULL,NULL),(NULL,NULL,'Pachewar',1217,1,NULL,NULL,NULL),(NULL,NULL,'Pachmarhi',1218,1,NULL,NULL,NULL),(NULL,NULL,'Pahalgam',1219,1,NULL,NULL,NULL),(NULL,NULL,'Palakkad',1220,1,NULL,NULL,NULL),(NULL,NULL,'Palampur',1221,1,NULL,NULL,NULL),(NULL,NULL,'Palanpur',1222,1,NULL,NULL,NULL),(NULL,NULL,'Pali',1223,1,NULL,NULL,NULL),(NULL,NULL,'Panchgani',1224,1,NULL,NULL,NULL),(NULL,NULL,'Panchkula',1225,1,NULL,NULL,NULL),(NULL,NULL,'Pangong',1226,1,NULL,NULL,NULL),(NULL,NULL,'Panna',1227,1,NULL,NULL,NULL),(NULL,NULL,'Paradeep',1228,1,NULL,NULL,NULL),(NULL,NULL,'Paragpur',1229,1,NULL,NULL,NULL),(NULL,NULL,'Parwanoo',1230,1,NULL,NULL,NULL),(NULL,NULL,'Pathankot',1231,1,NULL,NULL,NULL),(NULL,NULL,'Patna',1232,1,NULL,NULL,NULL),(NULL,NULL,'Patnitop',1233,1,NULL,NULL,NULL),(NULL,NULL,'Pelling',1234,1,NULL,NULL,NULL),(NULL,NULL,'Pemayangtse',1235,1,NULL,NULL,NULL),(NULL,NULL,'Pench',1236,1,NULL,NULL,NULL),(NULL,NULL,'Phalodi',1237,1,NULL,NULL,NULL),(NULL,NULL,'Pinjore',1238,1,NULL,NULL,NULL),(NULL,NULL,'Pondicherry',1239,1,NULL,NULL,NULL),(NULL,NULL,'Poovar',1240,1,NULL,NULL,NULL),(NULL,NULL,'Porbandar',1241,1,NULL,NULL,NULL),(NULL,NULL,'Port Blair',1242,1,NULL,NULL,NULL),(NULL,NULL,'Pragpur',1243,1,NULL,NULL,NULL),(NULL,NULL,'Puri',1244,1,NULL,NULL,NULL),(NULL,NULL,'Pushkar',1245,1,NULL,NULL,NULL),(NULL,NULL,'Puttaparthy',1246,1,NULL,NULL,NULL),(NULL,NULL,'Raichak',1247,1,NULL,NULL,NULL),(NULL,NULL,'Raipur',1248,1,NULL,NULL,NULL),(NULL,NULL,'Rajkot',1249,1,NULL,NULL,NULL),(NULL,NULL,'Rajsamand',1250,1,NULL,NULL,NULL),(NULL,NULL,'Ramgarh',1251,1,NULL,NULL,NULL),(NULL,NULL,'Ranakpur',1252,1,NULL,NULL,NULL),(NULL,NULL,'Ranchi',1253,1,NULL,NULL,NULL),(NULL,NULL,'Ranikhet',1254,1,NULL,NULL,NULL),(NULL,NULL,'Ranthambore',1255,1,NULL,NULL,NULL),(NULL,NULL,'Rishikesh',1256,1,NULL,NULL,NULL),(NULL,NULL,'Roha Raigad',1257,1,NULL,NULL,NULL),(NULL,NULL,'Rohet',1258,1,NULL,NULL,NULL),(NULL,NULL,'Ropar',1259,1,NULL,NULL,NULL),(NULL,NULL,'Rourkela',1260,1,NULL,NULL,NULL),(NULL,NULL,'Saputara',1261,1,NULL,NULL,NULL),(NULL,NULL,'Sarchu',1262,1,NULL,NULL,NULL),(NULL,NULL,'Sardargarh',1263,1,NULL,NULL,NULL),(NULL,NULL,'Sariska',1264,1,NULL,NULL,NULL),(NULL,NULL,'Sasangir',1265,1,NULL,NULL,NULL),(NULL,NULL,'Sawai Madhopur',1266,1,NULL,NULL,NULL),(NULL,NULL,'Sawantwadi',1267,1,NULL,NULL,NULL),(NULL,NULL,'Secundrabad',1268,1,NULL,NULL,NULL),(NULL,NULL,'Shekhawati',1269,1,NULL,NULL,NULL),(NULL,NULL,'Shillong',1270,1,NULL,NULL,NULL),(NULL,NULL,'Shirdi',1271,1,NULL,NULL,NULL),(NULL,NULL,'Siana',1272,1,NULL,NULL,NULL),(NULL,NULL,'Siliguri',1273,1,NULL,NULL,NULL),(NULL,NULL,'Silvassa',1274,1,NULL,NULL,NULL),(NULL,NULL,'Solapur',1275,1,NULL,NULL,NULL),(NULL,NULL,'Somnath',1276,1,NULL,NULL,NULL),(NULL,NULL,'Sravasti',1277,1,NULL,NULL,NULL),(NULL,NULL,'Srinagar',1278,1,NULL,NULL,NULL),(NULL,NULL,'Surat',1279,1,NULL,NULL,NULL),(NULL,NULL,'Taragarh',1280,1,NULL,NULL,NULL),(NULL,NULL,'Tawang',1281,1,NULL,NULL,NULL),(NULL,NULL,'Tezpur',1282,1,NULL,NULL,NULL),(NULL,NULL,'Thanjavur',1283,1,NULL,NULL,NULL),(NULL,NULL,'Thattekkadu',1284,1,NULL,NULL,NULL),(NULL,NULL,'Thekkady',1285,1,NULL,NULL,NULL),(NULL,NULL,'Thrissur',1286,1,NULL,NULL,NULL),(NULL,NULL,'Tiruchirapalli',1287,1,NULL,NULL,NULL),(NULL,NULL,'Tirupati',1288,1,NULL,NULL,NULL),(NULL,NULL,'Trivandrum',1289,1,NULL,NULL,NULL),('vvcbvcbv','','Udaipur',1290,1,NULL,NULL,NULL),(NULL,NULL,'Udhampur',1291,1,NULL,NULL,NULL),(NULL,NULL,'Ujjain',1292,1,NULL,NULL,NULL),(NULL,NULL,'Uttarkashi',1293,1,NULL,NULL,NULL),(NULL,NULL,'Vadodara',1294,1,NULL,NULL,NULL),(NULL,NULL,'Vailankanni',1295,1,NULL,NULL,NULL),(NULL,NULL,'Vapi',1296,1,NULL,NULL,NULL),('dgfhdttyujtdy',NULL,'Varanasi',1297,1,NULL,NULL,NULL),(NULL,NULL,'Varkala',1298,1,NULL,NULL,NULL),(NULL,NULL,'Vellore',1299,1,NULL,NULL,NULL),(NULL,NULL,'Vijaywada',1300,1,NULL,NULL,NULL),(NULL,NULL,'Visakhapatnam',1301,1,NULL,NULL,NULL),(NULL,NULL,'Wayanad',1302,1,NULL,NULL,NULL),(NULL,NULL,'Yamunanagar',1303,1,NULL,NULL,NULL),(NULL,NULL,'Yamunotri',1304,1,NULL,NULL,NULL),('fghghgjghjh',NULL,'Yercaud',1305,1,NULL,NULL,NULL),('gvjhyuikfghfh',NULL,'Test City',1306,1,45,54,NULL),('Gurgaon','GAO','Gurgaon',1307,1,NULL,NULL,NULL),('Its famous for litchi','MFP','Muzaffarpur',1310,1,34,12,NULL),('super locations in the city','LAT','LATESt city',1322,1,22,12,NULL),('asxvfdadsv','ALR','alrdfds',1323,1,12,11,NULL),('sdf','123W4','qswefwref',1325,1,12,1,NULL),('ojojjojo','98989','Tata',1326,1,98,98,NULL),('At the heart of the City','','Tisco',1327,1,120,82,NULL),('biuril',NULL,'Berut',1328,1,NULL,NULL,NULL),('awesome','ABCD','xyz',1332,1,NULL,NULL,NULL),('awesome','abc','abc+_)(*^$#@',1334,1,567,123,NULL),('japan','CS24','japan',1335,1,567,100,NULL),('7#  street macu road,,','DF','gfhgh',1336,1,74,82,NULL),('sdgfd','A001','Tunisha',1337,149,180,70,NULL),('avbjhnjnaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','1123','test city 1212',1338,1,NULL,NULL,NULL),('mmmmmmmmmmmmmmmmmmmmmmmllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllppppppppppppppppppppppppppppppppppppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaapppppppppppppppppppppppppppppppppaaaaaaaaaaaaaaaaaaaaaaaaaaaaaappppppppppppppppppppppppppp','1233','hgjj',1339,1,NULL,NULL,NULL),('sdf','E0480','dfsdf',1340,149,180,70,NULL),('dfsdfsdf','A121','dafsdf',1341,149,NULL,NULL,NULL),('Capital of Jharkhand','BFS','Bahrampur',1342,1,120,70,NULL),('No Information available','A001','Latvia',1343,142,122,70,NULL),('adskasd','W4','Andora Capital',1344,134,140,70,NULL),('Taj','AGRA','Agra',1345,1,180,80,NULL),('SultanPur is great place.','SLN','Sultanpur',1346,1,12,12,NULL),('Faizabad is great place.','FZD','Faizabad',1347,1,NULL,NULL,NULL),('colombo is city big state for Lord Buddha ','23','Colombo',1348,113,3.2,2.3,NULL),('Yala city for tourist guide','YALA','Yala',1349,113,0.5,1.2,NULL),('Maldivs of package tourist planned','#$W@1','Maldivs',1350,113,1.2,-0.4,NULL),('colombo is city big state for Lord Buddha ','SW@1C','Srtilnkan',1351,113,1.3,-0.4,NULL),('nagar is a samll city in gujrat.','GDN','Gandhnagar',1352,1,50,50,NULL),('Singapore','SPR','Singapore',1353,11,112,112,NULL),('Bukit Panjang  Zhenghu Bukit Panjang','ABC','Bukit Panjang',1354,11,2.1,1.2,NULL),('Kathmandu (Nepali: à¤•à¤¾à¤ à¤®à¤¾à¤¡à¥Œà¤‚ [kÉ‘ÊˆÊ°mÉ‘É³É–u]; Nepal Bhasa: à¤¯à¥‡à¤ à¤¦à¥‡à¤¯à¥â€Œ) is the capital and largest urban agglomerate of Nepal. ','NKC01','Katmandhu',1355,6,NULL,NULL,NULL);

/*Table structure for table `country` */

DROP TABLE IF EXISTS `country`;

CREATE TABLE `country` (
  `country_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `country_name` varchar(64) DEFAULT NULL,
  `country_code` varchar(5) DEFAULT NULL,
  `country_info` text,
  PRIMARY KEY (`country_id`),
  KEY `country_name` (`country_name`)
) ENGINE=InnoDB AUTO_INCREMENT=150 DEFAULT CHARSET=utf8;

/*Data for the table `country` */

insert  into `country`(`country_id`,`country_name`,`country_code`,`country_info`) values (1,'India','IND','IN'),(3,'USA','USA','USA'),(4,'France','FRA','Fr'),(5,'Bhutan','BHU','BHU'),(6,'nepal','NP','NP'),(7,'Spain','SPA','SPA'),(8,'United Kingdom','UK','UK'),(9,'Japan','JPN','JPN'),(10,'Sweden','SWE','SWE'),(11,'Singapore','SIN','SIN'),(12,'Aruba','ABW',NULL),(13,'Albania','ALB',NULL),(15,'Argentina','ARG',NULL),(16,'Armenia','ARM',NULL),(17,'Antigua & Barbuda','ATG',NULL),(18,'Austria','AUS',NULL),(19,'Australia','AUT',NULL),(20,'Azerbaijan','AZE',NULL),(21,'Belgium','BEL',NULL),(22,'Bahrain','BHR',NULL),(23,'Bahamas','BHS',NULL),(24,'Belarus','BLR',NULL),(25,'Bosnia & Herzegovina','BOS',NULL),(26,'Brazil','BRA',NULL),(27,'Barbados','BRB',NULL),(28,'Bulgaria','BUL',NULL),(29,'Canada','CAN',NULL),(30,'China','CHN',NULL),(31,'Croatia','CRO',NULL),(32,'Cuba','CUB',NULL),(33,'Curacao','CUW',NULL),(34,'Cyprus','CYP',NULL),(35,'Czech Republic','CZE',NULL),(36,'Denmark','DEN',NULL),(37,'Egypt','EGY',NULL),(38,'Estonia','EST',NULL),(39,'Finland','FIN',NULL),(41,'Georgia','GEO',NULL),(42,'Germany','GER',NULL),(43,'Gibraltar','GIB',NULL),(44,'Grenada','GRD',NULL),(45,'Greece','GRE',NULL),(46,'Hong Kong','HKG',NULL),(47,'Hungary','HUN',NULL),(48,'Iceland','ICE',NULL),(49,'Indonesia','IDN',NULL),(51,'Ireland','IRE',NULL),(52,'Israel','ISR',NULL),(53,'Italy','ITA',NULL),(54,'Jamaica','JAM',NULL),(55,'Jordan','JOR',NULL),(57,'Kazakhstan','KAZ',NULL),(58,'Cambodia','KHM',NULL),(59,'South Korea','KOR',NULL),(60,'Latvia','LAT',NULL),(61,'Lebanon','LBN',NULL),(62,'St Lucia','LCA',NULL),(63,'Lithuania','LIT',NULL),(64,'Luxembourg','LUX',NULL),(65,'Macau','MAC',NULL),(66,'Morocco','MAR',NULL),(67,'Maldives','MDV',NULL),(68,'Mexico','MEX',NULL),(69,'Malta','MLA',NULL),(70,'Moldova','MOL',NULL),(71,'Monaco','MON',NULL),(72,'Montenegro','MTN',NULL),(73,'Mauritius','MUS',NULL),(74,'Malaysia','MYS',NULL),(75,'Netherlands','NET',NULL),(76,'New Zealand','NEZ',NULL),(77,'Norway','NOR',NULL),(78,'Oman','OMN',NULL),(79,'Poland','POL',NULL),(80,'Portugal','POR',NULL),(81,'Puerto Rico','PRI',NULL),(82,'Qatar','QAT',NULL),(83,'Romania','ROM',NULL),(84,'Russia','RUS',NULL),(85,'Saudi Arabia','SAU',NULL),(86,'Serbia','SER',NULL),(88,'Slovakia','SLO',NULL),(89,'Slovenia','SLV','Slovenia'),(92,'Switzerland','SWI','Honeymoon Place'),(93,'Thailand','THA','Thailand'),(94,'Turkey','TUR','Turkey info'),(95,'Taiwan','TWN','Taiwan info'),(97,'Ukraine','UKR','Ukraine info'),(98,'Uruguay','URY','Uruguay'),(100,'Uzbekistan','UZB','Uzbekistan'),(101,'Vietnam','VNM','Vietnam europe'),(102,'South Africa','ZAF','Aferica country '),(103,'Fiji','Fiji','Fiji'),(104,'Western Samoa','Samoa','Western Samoa'),(106,'Cook Island','Cook ','Cook Island'),(107,'American Samoa','Ameri','American Samoa'),(108,'Easter Island','Easte','Easter Island'),(109,'French Polynesia','Frenc','French Polynesia'),(110,'Hawaii','Hawai','Hawaiiiiiki'),(111,'Tonga','Tonga','Tongaaaaaa'),(112,'Norfolk Island','Norfo','Norfolk Islandddd'),(113,'Srilanka','Srila','Srilankaaaaa'),(114,'British Virgin Islands','Briti','British Virgin Islands'),(115,'Cayman Islands','Cayma','Cayman Islands'),(116,'Dominican Republic','Domin','Dominican Republic'),(118,'Guadeloupe','Guade','Guadeloupe'),(119,'Haiti','Haiti','Haiti'),(120,'Martinique','Marti','Martinique'),(123,'Trinidad AND Tobago','Trini','Trinidad AND Tobago'),(124,'Saint Kitts AND Nevis','Saint','Saint Kitts AND Nevis'),(125,'Bolivia','Boliv','Bolivia'),(126,'Chile','Chile','Chile'),(127,'Ecuador','Ecuad','Ecuador'),(128,'Colombia','Colom','Colombia'),(129,'French Guiana','Frenc','French Guiana'),(130,'Guyana','Guyan','Guyana'),(131,'Paraguay','Parag','Paraguay'),(132,'Peru','Peru','Peru'),(133,'Venezuela','Venez','Venezuela'),(134,'Andorra','Andor','Andorra'),(136,'Italy','Italy','Italy'),(137,'Liechtenstein','Liech','Liechtenstein'),(138,'Republic of Macedonia','Repub','Republic of Macedonia'),(139,'Vatican','Vatic','Vatican'),(142,'Kuwait','Kuwai','Kuwait'),(143,'Syria','Syria','Syria'),(144,'Yemen','Yemen','Yemen'),(145,'Algeria','Alger','Algeria'),(147,'Somalia','Somal','Somalia'),(149,'Zimbabwe','Zimba','Zimbabwe');

/*Table structure for table `currency` */

DROP TABLE IF EXISTS `currency`;

CREATE TABLE `currency` (
  `currency_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `currency_code` char(3) NOT NULL,
  `currency_name` varchar(45) NOT NULL,
  `currency_symbol` char(3) NOT NULL,
  PRIMARY KEY (`currency_id`),
  KEY `currency_code` (`currency_code`)
) ENGINE=InnoDB AUTO_INCREMENT=149 DEFAULT CHARSET=utf8;

/*Data for the table `currency` */

insert  into `currency`(`currency_id`,`currency_code`,`currency_name`,`currency_symbol`) values (1,'AFA','Afghanistan afghani','$'),(2,'ALL','Albanian lek',''),(3,'DZD','Algerian dinar',''),(4,'AOR','Angolan kwanza reajustado',''),(5,'ARS','Argentine peso',''),(6,'AMD','Armenian dram',''),(7,'AWG','Aruban guilder',''),(8,'AUD','Australian dollar',''),(9,'AZN','Azerbaijanian new manat',''),(10,'BSD','Bahamian dollar',''),(11,'BHD','Bahraini dinar',''),(12,'BDT','Bangladeshi taka',''),(13,'BBD','Barbados dollar',''),(14,'BYR','Belarusian ruble',''),(15,'BZD','Belize dollar',''),(16,'BMD','Bermudian dollar',''),(17,'BTN','Bhutan ngultrum',''),(18,'BOB','Bolivian boliviano',''),(19,'BWP','Botswana pula',''),(20,'BRL','Brazilian real',''),(21,'GBP','British pound',''),(22,'BND','Brunei dollar',''),(23,'BGN','Bulgarian lev',''),(24,'BIF','Burundi franc',''),(25,'KHR','Cambodian riel',''),(26,'CAD','Canadian dollar',''),(27,'CVE','Cape Verde escudo',''),(28,'KYD','Cayman Islands dollar',''),(29,'XOF','CFA franc BCEAO',''),(30,'XAF','CFA franc BEAC',''),(31,'XPF','CFP franc',''),(32,'CLP','Chilean peso',''),(33,'CNY','Chinese yuan renminbi',''),(34,'COP','Colombian peso',''),(35,'KMF','Comoros franc',''),(36,'CDF','Congolese franc',''),(37,'CRC','Costa Rican colon',''),(38,'HRK','Croatian kuna',''),(39,'CUP','Cuban peso',''),(40,'CZK','Czech koruna',''),(41,'DKK','Danish krone',''),(42,'DJF','Djibouti franc',''),(43,'DOP','Dominican peso',''),(44,'XCD','East Caribbean dollar',''),(45,'EGP','Egyptian pound',''),(46,'SVC','El Salvador colon',''),(47,'ERN','Eritrean nakfa',''),(48,'EEK','Estonian kroon',''),(49,'ETB','Ethiopian birr',''),(50,'EUR','EU euro',''),(51,'FKP','Falkland Islands pound',''),(52,'FJD','Fiji dollar',''),(53,'GMD','Gambian dalasi',''),(54,'GEL','Georgian lari',''),(55,'GHS','Ghanaian new cedi',''),(56,'GIP','Gibraltar pound',''),(57,'XAU','Gold (ounce)',''),(58,'XFO','Gold franc',''),(59,'GTQ','Guatemalan quetzal',''),(60,'GNF','Guinean franc',''),(61,'GYD','Guyana dollar',''),(62,'HTG','Haitian gourde',''),(63,'HNL','Honduran lempira',''),(64,'HKD','Hong Kong SAR dollar',''),(65,'HUF','Hungarian forint',''),(66,'ISK','Icelandic krona',''),(67,'XDR','IMF special drawing right',''),(68,'INR','Indian rupee','Rs.'),(69,'IDR','Indonesian rupiah',''),(70,'IRR','Iranian rial',''),(71,'IQD','Iraqi dinar',''),(72,'ILS','Israeli new shekel',''),(73,'JMD','Jamaican dollar',''),(74,'JPY','Japanese yen',''),(75,'JOD','Jordanian dinar',''),(76,'KZT','Kazakh tenge',''),(77,'KES','Kenyan shilling',''),(78,'KWD','Kuwaiti dinar',''),(79,'KGS','Kyrgyz som',''),(80,'LAK','Lao kip',''),(81,'LVL','Latvian lats',''),(82,'LBP','Lebanese pound',''),(83,'LSL','Lesotho loti',''),(84,'LRD','Liberian dollar',''),(85,'LYD','Libyan dinar',''),(86,'LTL','Lithuanian litas',''),(87,'MOP','Macao SAR pataca',''),(88,'MKD','Macedonian denar',''),(89,'MGA','Malagasy ariary',''),(90,'MWK','Malawi kwacha',''),(91,'MYR','Malaysian ringgit',''),(92,'MVR','Maldivian rufiyaa',''),(93,'MRO','Mauritanian ouguiya',''),(94,'MUR','Mauritius rupee',''),(95,'MXN','Mexican peso',''),(96,'MDL','Moldovan leu',''),(97,'MNT','Mongolian tugrik',''),(98,'MAD','Moroccan dirham',''),(99,'MZN','Mozambique new metical',''),(100,'MMK','Myanmar kyat',''),(101,'NAD','Namibian dollar',''),(102,'NPR','Nepalese rupee',''),(103,'ANG','Netherlands Antillian guilder',''),(104,'NZD','New Zealand dollar',''),(105,'NIO','Nicaraguan cordoba oro',''),(106,'NGN','Nigerian naira',''),(107,'KPW','North Korean won',''),(108,'NOK','Norwegian krone',''),(109,'OMR','Omani rial',''),(110,'PKR','Pakistani rupee',''),(111,'XPD','Palladium (ounce)',''),(112,'PAB','Panamanian balboa',''),(113,'PGK','Papua New Guinea kina',''),(114,'PYG','Paraguayan guarani',''),(115,'PEN','Peruvian nuevo sol',''),(116,'PHP','Philippine peso',''),(117,'XPT','Platinum (ounce)',''),(118,'PLN','Polish zloty',''),(119,'QAR','Qatari rial',''),(120,'RON','Romanian new leu',''),(121,'RUB','Russian ruble',''),(122,'RWF','Rwandan franc',''),(123,'SHP','Saint Helena pound',''),(124,'WST','Samoan tala',''),(125,'STD','Sao Tome and Principe dobra',''),(126,'SAR','Saudi riyal',''),(127,'RSD','Serbian dinar',''),(128,'SCR','Seychelles rupee',''),(129,'SLL','Sierra Leone leone',''),(130,'XAG','Silver (ounce)',''),(131,'SGD','Singapore dollar',''),(132,'SBD','Solomon Islands dollar',''),(133,'SOS','Somali shilling',''),(134,'ZAR','South African rand',''),(135,'KRW','South Korean won',''),(136,'LKR','Sri Lanka rupee',''),(137,'SDG','Sudanese pound',''),(138,'SRD','Suriname dollar',''),(139,'SZL','Swaziland lilangeni',''),(140,'SEK','Swedish krona',''),(141,'CHF','Swiss franc',''),(142,'SYP','Syrian pound',''),(143,'TWD','Taiwan New dollar',''),(144,'TJS','Tajik somoni',''),(145,'TZS','Tanzanian shilling',''),(146,'THB','Thai baht',''),(147,'USD','Dollar',''),(148,'PDS','Pounds','£');

/*Table structure for table `department` */

DROP TABLE IF EXISTS `department`;

CREATE TABLE `department` (
  `department_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `department_name` varchar(64) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '0',
  `description` varchar(2000) DEFAULT NULL,
  `default_department` int(1) DEFAULT NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE KEY `comp_department_customer_id` (`department_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `department` */

/*Table structure for table `feedback` */

DROP TABLE IF EXISTS `feedback`;

CREATE TABLE `feedback` (
  `FId` int(10) NOT NULL AUTO_INCREMENT,
  `UserID` varchar(100) DEFAULT NULL,
  `Feedback` text,
  `DateSubmitted` date DEFAULT NULL,
  PRIMARY KEY (`FId`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

/*Data for the table `feedback` */

insert  into `feedback`(`FId`,`UserID`,`Feedback`,`DateSubmitted`) values (1,'kalyan','We choose Goa .Their service is very nice','2008-02-18');

/*Table structure for table `invites` */

DROP TABLE IF EXISTS `invites`;

CREATE TABLE `invites` (
  `Sno` int(10) NOT NULL AUTO_INCREMENT,
  `From` varchar(200) NOT NULL DEFAULT '',
  `To` varchar(200) DEFAULT NULL,
  `Status` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`Sno`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `invites` */

insert  into `invites`(`Sno`,`From`,`To`,`Status`) values (1,'kalyan','xyz@gmail.com,ghij@yahoo.com','Invited'),(2,'kalyan','Raj@gmail.com,James@yahoo.com','Invited'),(3,'kalyan','Raju@gmail.com,\r\nRamu@yahoo.com','Invite');

/*Table structure for table `lob` */

DROP TABLE IF EXISTS `lob`;

CREATE TABLE `lob` (
  `lob_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `lob_name` varchar(64) DEFAULT NULL,
  `lob_location` bigint(20) DEFAULT NULL,
  `lob_head` varchar(64) DEFAULT NULL,
  `lob_desc` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`lob_id`),
  KEY `FK_lob_location` (`lob_location`),
  CONSTRAINT `FK_lob_location` FOREIGN KEY (`lob_location`) REFERENCES `location` (`location_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

/*Data for the table `lob` */

insert  into `lob`(`lob_id`,`lob_name`,`lob_location`,`lob_head`,`lob_desc`) values (1,'BAP',1,'1','1'),(2,'PES',2,'2','2'),(3,'abc',3,'3','3'),(4,'bap',1,'SDSDDSscsc','bap'),(5,'ABC',1,'sqqw','ABC'),(6,'SDSDFDFSF',1,'qwsass','SDSDFDFSF'),(7,'bap',1,'qwsass','bap'),(8,'bap',1,'qwsass','bap'),(9,'SDSDFDFSF',2,'qwsass','SDSDFDFSF');

/*Table structure for table `location` */

DROP TABLE IF EXISTS `location`;

CREATE TABLE `location` (
  `location_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `location_name` varchar(64) DEFAULT NULL,
  `location_code` varchar(64) DEFAULT NULL,
  `location_desc` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`location_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `location` */

insert  into `location`(`location_id`,`location_name`,`location_code`,`location_desc`) values (1,'INDIA','IND','india'),(2,'UK','UK','UK'),(3,'USA','USA','USA'),(4,'SINGAPORE','SINGAPORE','sing');

/*Table structure for table `login` */

DROP TABLE IF EXISTS `login`;

CREATE TABLE `login` (
  `UserID` varchar(200) DEFAULT NULL,
  `Password` varchar(200) DEFAULT NULL,
  `Auth` varchar(200) DEFAULT NULL,
  `user_type` bigint(29) DEFAULT NULL,
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  KEY `FK_login` (`user_type`),
  CONSTRAINT `FK_login` FOREIGN KEY (`user_type`) REFERENCES `user_type` (`user_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=latin1;

/*Data for the table `login` */

insert  into `login`(`UserID`,`Password`,`Auth`,`user_type`,`id`) values ('admin','admin','1',1,1),('kalyan','kalyan','2',2,2),('Nita','Nita','2',4,3),('pankaj','pankaj','1',3,4),('Rahul','Rahul','2',2,5),('Rajesh','raj','2',3,6),('Ram','ram','1',4,7),('Subhas','Subhas','1',3,8),('pop','pop','1',1,14);

/*Table structure for table `manager` */

DROP TABLE IF EXISTS `manager`;

CREATE TABLE `manager` (
  `manager_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `manager_name` varchar(64) DEFAULT NULL,
  `manager_emp_id` varchar(10) DEFAULT NULL,
  `manager_dept_id` bigint(20) DEFAULT NULL,
  `manager_lob_id` bigint(20) DEFAULT NULL,
  `manager_account_id` bigint(20) DEFAULT NULL,
  `manager_location_id` bigint(20) DEFAULT NULL,
  `manager_currency` bigint(20) DEFAULT NULL,
  `manager_descrition` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`manager_id`),
  KEY `FK_manager` (`manager_currency`),
  KEY `FK_manager_location` (`manager_location_id`),
  KEY `FK_manager_lob` (`manager_lob_id`),
  KEY `FK_manager_acct` (`manager_account_id`),
  CONSTRAINT `FK_manager_acct` FOREIGN KEY (`manager_account_id`) REFERENCES `account` (`account_id`),
  CONSTRAINT `FK_manager` FOREIGN KEY (`manager_currency`) REFERENCES `currency` (`currency_id`),
  CONSTRAINT `FK_manager_lob` FOREIGN KEY (`manager_lob_id`) REFERENCES `lob` (`lob_id`),
  CONSTRAINT `FK_manager_location` FOREIGN KEY (`manager_location_id`) REFERENCES `location` (`location_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `manager` */

insert  into `manager`(`manager_id`,`manager_name`,`manager_emp_id`,`manager_dept_id`,`manager_lob_id`,`manager_account_id`,`manager_location_id`,`manager_currency`,`manager_descrition`) values (1,'zzxzxxzx','sddasdasda',1,1,1,1,1,'asccsaassdcsd'),(2,'Pankaj Amal','123456',1,1,1,1,1,'csdcdscsdcdscsd'),(3,'zzxzxxzx','sddasdasda',1,2,1,1,1,'rweewrewrw');

/*Table structure for table `module` */

DROP TABLE IF EXISTS `module`;

CREATE TABLE `module` (
  `module_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `module_name` varchar(20) DEFAULT NULL,
  `module_description` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`module_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `module` */

insert  into `module`(`module_id`,`module_name`,`module_description`) values (1,'Project','This is project'),(2,'Project Manager','PM'),(3,'Account','account'),(4,'LOB','Line of business');

/*Table structure for table `priority` */

DROP TABLE IF EXISTS `priority`;

CREATE TABLE `priority` (
  `priority_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `priority_code` varchar(10) DEFAULT NULL,
  `priority_desc` varbinary(64) DEFAULT NULL,
  PRIMARY KEY (`priority_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

/*Data for the table `priority` */

insert  into `priority`(`priority_id`,`priority_code`,`priority_desc`) values (1,'TIME','TIME'),(2,'COST','COST'),(3,'PERFORMANC','PERFORMANCE');

/*Table structure for table `project` */

DROP TABLE IF EXISTS `project`;

CREATE TABLE `project` (
  `project_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `project_name` varchar(64) DEFAULT NULL,
  `project_lob` bigint(20) DEFAULT NULL,
  `project_account` bigint(20) DEFAULT NULL,
  `project_base_currency` bigint(20) DEFAULT NULL,
  `project_priority` bigint(20) DEFAULT NULL,
  `project_status` bigint(20) DEFAULT NULL,
  `project_type` bigint(20) DEFAULT NULL,
  `start_date` datetime DEFAULT NULL,
  `end_date` datetime DEFAULT NULL,
  `project_desc` varchar(255) DEFAULT NULL,
  `pm_id` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`project_id`,`pm_id`),
  KEY `FK_project` (`pm_id`),
  KEY `FK_lob` (`project_lob`),
  KEY `FK_currency` (`project_base_currency`),
  KEY `FK_type` (`project_type`),
  KEY `FK_priority` (`project_priority`),
  KEY `FK_account` (`project_account`),
  KEY `FK_status` (`project_status`),
  CONSTRAINT `FK_account` FOREIGN KEY (`project_account`) REFERENCES `account` (`account_id`),
  CONSTRAINT `FK_currency` FOREIGN KEY (`project_base_currency`) REFERENCES `currency` (`currency_id`),
  CONSTRAINT `FK_lob` FOREIGN KEY (`project_lob`) REFERENCES `lob` (`lob_id`),
  CONSTRAINT `FK_priority` FOREIGN KEY (`project_priority`) REFERENCES `priority` (`priority_id`),
  CONSTRAINT `FK_project` FOREIGN KEY (`pm_id`) REFERENCES `manager` (`manager_id`),
  CONSTRAINT `FK_status` FOREIGN KEY (`project_status`) REFERENCES `status` (`status_id`),
  CONSTRAINT `FK_type` FOREIGN KEY (`project_type`) REFERENCES `type` (`type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=latin1;

/*Data for the table `project` */

insert  into `project`(`project_id`,`project_name`,`project_lob`,`project_account`,`project_base_currency`,`project_priority`,`project_status`,`project_type`,`start_date`,`end_date`,`project_desc`,`pm_id`) values (22,'PQR',1,1,1,1,1,1,NULL,NULL,'xzxczxczczc',2);

/*Table structure for table `resortsinfo` */

DROP TABLE IF EXISTS `resortsinfo`;

CREATE TABLE `resortsinfo` (
  `ResortID` varchar(100) NOT NULL,
  `LocationName` varchar(100) DEFAULT NULL,
  `ResortImage` varchar(200) DEFAULT NULL,
  `NoOfRooms` int(50) DEFAULT NULL,
  `NoOfRoomsAvailable` int(50) DEFAULT NULL,
  `Restaurant` varchar(100) DEFAULT NULL,
  `Swimmingpool` varchar(100) DEFAULT NULL,
  `GamesRoom` varchar(100) DEFAULT NULL,
  `Casino` varchar(100) DEFAULT NULL,
  `YogaandMeditation` varchar(100) DEFAULT NULL,
  `SteamBath` varchar(100) DEFAULT NULL,
  `GymandHealthCenter` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ResortID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `resortsinfo` */

insert  into `resortsinfo`(`ResortID`,`LocationName`,`ResortImage`,`NoOfRooms`,`NoOfRoomsAvailable`,`Restaurant`,`Swimmingpool`,`GamesRoom`,`Casino`,`YogaandMeditation`,`SteamBath`,`GymandHealthCenter`) values ('R001','Goa','GoaResort.jpg',6,6,'Yes','Yes','Yes','No','Yes','No','No'),('R002','Coorg','CoorgResort.jpg',6,6,'Yes','No','Yes','Yes','No','Yes','Yes'),('R003','Manali','ManaliResort.jpg',5,5,'Yes','Yes','Yes','Yes','Yes','Yes','Yes'),('R004','Kodaikanal','KodaikanalResort.jpg',5,5,'Yes','Yes','No','No','Yes','Yes','Yes'),('R005','Munnar','MunnarResort.jpg',6,6,'Yes','No','No','No','Yes','Yes','Yes');

/*Table structure for table `roomsinfo` */

DROP TABLE IF EXISTS `roomsinfo`;

CREATE TABLE `roomsinfo` (
  `Sno` varchar(100) NOT NULL,
  `RoomID` varchar(100) DEFAULT NULL,
  `ResortID` varchar(100) DEFAULT NULL,
  `LocationName` varchar(100) DEFAULT NULL,
  `RoomType` varchar(100) DEFAULT NULL,
  `RoomArea` varchar(100) DEFAULT NULL,
  `DryKitchenette` varchar(100) DEFAULT NULL,
  `SofacumBed` varchar(100) DEFAULT NULL,
  `DoubleBeds` varchar(100) DEFAULT NULL,
  `Telephone` varchar(100) DEFAULT NULL,
  `Television` varchar(100) DEFAULT NULL,
  `RoomCharges` float DEFAULT NULL,
  PRIMARY KEY (`Sno`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*Data for the table `roomsinfo` */

insert  into `roomsinfo`(`Sno`,`RoomID`,`ResortID`,`LocationName`,`RoomType`,`RoomArea`,`DryKitchenette`,`SofacumBed`,`DoubleBeds`,`Telephone`,`Television`,`RoomCharges`) values ('1','R0011','R001','Goa','StudioApartment','450','Yes','Yes','No','Yes','Yes',500),('2','R0012','R001','Goa','SingleBedRoomApartment','450','Yes','Yes','Yes','Yes','Yes',650),('3','R0013','R001','Goa','DoubleBedRoomApartment','650','Yes','Yes','Yes','Yes','Yes',750),('4','R0024','R002','Coorg','StudioApartment','450','Yes','Yes','No','Yes','Yes',500),('5','R0015','R001','Goa','SingleBedRoomApartment','450','Yes','No','No','Yes','Yes',550),('6','R0016','R001','Goa','StudioApartment','450','Yes','Yes','No','Yes','Yes',500),('7','R0017','R001','Goa','DoubleBedRoomApartment','600','Yes','Yes','Yes','Yes','Yes',600),('8','R0028','R002','Coorg','SingleBedRoomApartment','500','Yes','Yes','Yes','Yes','Yes',600),('9','R0059','R005','Munnar','StudioApartment','500','Yes','Yes','Yes','Yes','Yes',600);

/*Table structure for table `status` */

DROP TABLE IF EXISTS `status`;

CREATE TABLE `status` (
  `status_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `status_code` varchar(10) DEFAULT NULL,
  `status_desc` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`status_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

/*Data for the table `status` */

insert  into `status`(`status_id`,`status_code`,`status_desc`) values (1,'Active','Active'),(2,'Running','Running'),(3,'On Hold','On Hold'),(4,'Dropped','Dropped'),(5,'Completed','Completed');

/*Table structure for table `type` */

DROP TABLE IF EXISTS `type`;

CREATE TABLE `type` (
  `type_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `type_code` varchar(10) DEFAULT NULL,
  `type_desc` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1;

/*Data for the table `type` */

insert  into `type`(`type_id`,`type_code`,`type_desc`) values (1,'Single act','Single action'),(2,'Sequential','Sequential'),(3,'Parallel','Parallel'),(4,'Developmen','Development'),(5,'Testing','Testing'),(6,'Enhancemen','Enhancement');

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `regid` bigint(20) NOT NULL AUTO_INCREMENT,
  `userid` varchar(64) DEFAULT NULL,
  `FirstName` varchar(100) DEFAULT NULL,
  `LastName` varchar(100) DEFAULT NULL,
  `address` varchar(200) DEFAULT NULL,
  `emailaddress` varchar(64) DEFAULT NULL,
  `designation` bigint(20) DEFAULT NULL,
  `empid` varchar(20) DEFAULT NULL,
  `contactnumber` varchar(20) DEFAULT NULL,
  `user_type` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`regid`),
  KEY `FK_userprofile_usertype` (`user_type`),
  CONSTRAINT `FK_userprofile_usertype` FOREIGN KEY (`user_type`) REFERENCES `user_type` (`user_type_id`),
  CONSTRAINT `FK_userprofile` FOREIGN KEY (`regid`) REFERENCES `login` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `user` */

insert  into `user`(`regid`,`userid`,`FirstName`,`LastName`,`address`,`emailaddress`,`designation`,`empid`,`contactnumber`,`user_type`) values (1,'admin','adczxv',NULL,'  cdsdsssc`','dasad@dewdewd.com',1,'1234','12233213',1),(2,'TEst','adczxv',NULL,'DCDSCCS','dasad@dewdewd.com',2,'1234','SFFSF',2),(3,'pankaj','adczxv','Amal',' dcdcdsc','panak@qwee.com',1,'1234','csscsacsc',3),(4,'pop','Pankaj','Bhanu','gdffgfddgd','qww@sdsd.com',1,'1234','gfdgddf',1);

/*Table structure for table `user_type` */

DROP TABLE IF EXISTS `user_type`;

CREATE TABLE `user_type` (
  `user_type_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_type` varchar(20) DEFAULT NULL,
  `user_type_description` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`user_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Data for the table `user_type` */

insert  into `user_type`(`user_type_id`,`user_type`,`user_type_description`) values (1,'Admin','Admin'),(2,'Project Manager','Project Manager'),(3,'Account','Account Head'),(4,'LOB','LOB Head');

/*Table structure for table `wine` */

DROP TABLE IF EXISTS `wine`;

CREATE TABLE `wine` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `year` varchar(45) DEFAULT NULL,
  `grapes` varchar(45) DEFAULT NULL,
  `country` varchar(45) DEFAULT NULL,
  `region` varchar(45) DEFAULT NULL,
  `description` blob,
  `picture` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

/*Data for the table `wine` */

insert  into `wine`(`id`,`name`,`year`,`grapes`,`country`,`region`,`description`,`picture`) values (1,'CHATEAU DE SAINT COSME','2009','Grenache / Syrah','France','Southern Rhone / Gigondas','The aromas of fruit and spice give one a hint of the light drinkability of this lovely wine, which makes an excellent complement to fish dishes.','saint_cosme.jpg'),(2,'LAN RIOJA CRIANZA','2006','Tempranillo','Spain','Rioja','A resurgence of interest in boutique vineyards has opened the door for this excellent foray into the dessert wine market. Light and bouncy, with a hint of black truffle, this wine will not fail to tickle the taste buds.','lan_rioja.jpg'),(3,'MARGERUM SYBARITE','2010','Sauvignon Blanc','USA','California Central Cosat','The cache of a fine Cabernet in ones wine cellar can now be replaced with a childishly playful wine bubbling over with tempting tastes of\nblack cherry and licorice. This is a taste sure to transport you back in time.','margerum.jpg'),(4,'OWEN ROE \"EX UMBRIS\"','2009','Syrah','USA','Washington','A one-two punch of black pepper and jalapeno will send your senses reeling, as the orange essence snaps you back to reality. Don\'t miss\nthis award-winning taste sensation.','ex_umbris.jpg'),(5,'REX HILL','2009','Pinot Noir','USA','Oregon','One cannot doubt that this will be the wine served at the Hollywood award shows, because it has undeniable star power. Be the first to catch\nthe debut that everyone will be talking about tomorrow.','rex_hill.jpg'),(6,'VITICCIO CLASSICO RISERVA','2007','Sangiovese Merlot','Italy','Tuscany','Though soft and rounded in texture, the body of this wine is full and rich and oh-so-appealing. This delivery is even more impressive when one takes note of the tender tannins that leave the taste buds wholly satisfied.','viticcio.jpg'),(7,'CHATEAU LE DOYENNE','2005','Merlot','France','Bordeaux','Though dense and chewy, this wine does not overpower with its finely balanced depth and structure. It is a truly luxurious experience for the\nsenses.','le_doyenne.jpg'),(8,'DOMAINE DU BOUSCAT','2009','Merlot','France','Bordeaux','The light golden color of this wine belies the bright flavor it holds. A true summer wine, it begs for a picnic lunch in a sun-soaked vineyard.','bouscat.jpg'),(9,'BLOCK NINE','2009','Pinot Noir','USA','California','With hints of ginger and spice, this wine makes an excellent complement to light appetizer and dessert fare for a holiday gathering.','block_nine.jpg'),(10,'DOMAINE SERENE','2007','Pinot Noir','USA','Oregon','Though subtle in its complexities, this wine is sure to please a wide range of enthusiasts. Notes of pomegranate will delight as the nutty finish completes the picture of a fine sipping experience.','domaine_serene.jpg'),(11,'BODEGA LURTON','2011','Pinot Gris','Argentina','Mendoza','Solid notes of black currant blended with a light citrus make this wine an easy pour for varied palates.','bodega_lurton.jpg'),(12,'LES MORIZOTTES','2009','Chardonnay','France','Burgundy','Breaking the mold of the classics, this offering will surprise and undoubtedly get tongues wagging with the hints of coffee and tobacco in\nperfect alignment with more traditional notes. Breaking the mold of the classics, this offering will surprise and\nundoubtedly get tongues wagging with the hints of coffee and tobacco in\nperfect alignment with more traditional notes. Sure to please the late-night crowd with the slight jolt of adrenaline it brings.','morizottes.jpg');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
